function irACap(f)
{
	var cap = f.cap.value;
	var vers = f.vers.value;
	
	var ncaps = f.ncaps.value;
	cap = Number(cap);
//	alert("ahi vamos " + cap  + " / " + ncaps);
	
	if(! (cap >= 1 && cap <= ncaps)) {
		alert("capitulo invalido para este libro. Rango permitido: 1 a " +ncaps);
		return false;
	}
	cap = "x000" + cap;
	cap = "c" + cap.substring(cap.length-3,cap.length) + ".html";
	if(vers.length >0)
		cap = cap + "#v" + vers;		
//	alert("nos vamos a [" + cap + "]");	
	window.location = cap;	
}

function menuNavLibs(libro) { 
document.write('<div class="navlib"><i>Antiguo Testamento</i><br /><ul>');
if(libro == 'Gn') document.write('<li><b>Génesis</b></li>');
else document.write('<li><a href="../01_gn/c001.html">Génesis</a></li>');
if(libro == 'Ex') document.write('<li><b>Éxodo</b></li>');
else document.write('<li><a href="../02_ex/c001.html">Éxodo</a></li>');
if(libro == 'Lv') document.write('<li><b>Levítico</b></li>');
else document.write('<li><a href="../03_lv/c001.html">Levítico</a></li>');
if(libro == 'Nm') document.write('<li><b>Números</b></li>');
else document.write('<li><a href="../04_nm/c001.html">Números</a></li>');
if(libro == 'Dt') document.write('<li><b>Deuteronomio</b></li>');
else document.write('<li><a href="../05_dt/c001.html">Deuteronomio</a></li>');
if(libro == 'Jos') document.write('<li><b>Josué</b></li>');
else document.write('<li><a href="../06_jos/c001.html">Josué</a></li>');
if(libro == 'Jc') document.write('<li><b>Jueces</b></li>');
else document.write('<li><a href="../07_jc/c001.html">Jueces</a></li>');
if(libro == 'Rt') document.write('<li><b>Rut</b></li>');
else document.write('<li><a href="../08_rt/c001.html">Rut</a></li>');
if(libro == '1S') document.write('<li><b>I Samuel</b></li>');
else document.write('<li><a href="../09_1s/c001.html">I Samuel</a></li>');
if(libro == '2S') document.write('<li><b>II Samuel</b></li>');
else document.write('<li><a href="../10_2s/c001.html">II Samuel</a></li>');
if(libro == '1R') document.write('<li><b>I Reyes</b></li>');
else document.write('<li><a href="../11_1r/c001.html">I Reyes</a></li>');
if(libro == '2R') document.write('<li><b>II Reyes</b></li>');
else document.write('<li><a href="../12_2r/c001.html">II Reyes</a></li>');
if(libro == '1Cro') document.write('<li><b>I Crónicas</b></li>');
else document.write('<li><a href="../13_1cro/c001.html">I Crónicas</a></li>');
if(libro == '2Cro') document.write('<li><b>II Crónicas</b></li>');
else document.write('<li><a href="../14_2cro/c001.html">II Crónicas</a></li>');
if(libro == 'Esd') document.write('<li><b>Esdras</b></li>');
else document.write('<li><a href="../15_esd/c001.html">Esdras</a></li>');
if(libro == 'Ne') document.write('<li><b>Nehemías</b></li>');
else document.write('<li><a href="../16_ne/c001.html">Nehemías</a></li>');
if(libro == 'Tb') document.write('<li><b>Tobías</b></li>');
else document.write('<li><a href="../17_tb/c001.html">Tobías</a></li>');
if(libro == 'Jdt') document.write('<li><b>Judit</b></li>');
else document.write('<li><a href="../18_jdt/c001.html">Judit</a></li>');
if(libro == 'Est') document.write('<li><b>Ester</b></li>');
else document.write('<li><a href="../19_est/c001.html">Ester</a></li>');
if(libro == '1M') document.write('<li><b>I Macabeos</b></li>');
else document.write('<li><a href="../20_1m/c001.html">I Macabeos</a></li>');
if(libro == '2M') document.write('<li><b>II Macabeos</b></li>');
else document.write('<li><a href="../21_2m/c001.html">II Macabeos</a></li>');
if(libro == 'Jb') document.write('<li><b>Job</b></li>');
else document.write('<li><a href="../22_jb/c001.html">Job</a></li>');
if(libro == 'Sal') document.write('<li><b>Salmos</b></li>');
else document.write('<li><a href="../23_sal/c001.html">Salmos</a></li>');
if(libro == 'Pr') document.write('<li><b>Proverbios</b></li>');
else document.write('<li><a href="../24_pr/c001.html">Proverbios</a></li>');
if(libro == 'Qo') document.write('<li><b>Eclesiastés</b></li>');
else document.write('<li><a href="../25_qo/c001.html">Eclesiastés</a></li>');
if(libro == 'Ct') document.write('<li><b>Cantar de Cantares</b></li>');
else document.write('<li><a href="../26_ct/c001.html">Cantar de Cantares</a></li>');
if(libro == 'Sb') document.write('<li><b>Sabiduría</b></li>');
else document.write('<li><a href="../27_sb/c001.html">Sabiduría</a></li>');
if(libro == 'Si') document.write('<li><b>Eclesiástico</b></li>');
else document.write('<li><a href="../28_si/c001.html">Eclesiástico</a></li>');
if(libro == 'Is') document.write('<li><b>Isaías</b></li>');
else document.write('<li><a href="../29_is/c001.html">Isaías</a></li>');
if(libro == 'Jr') document.write('<li><b>Jeremías</b></li>');
else document.write('<li><a href="../30_jr/c001.html">Jeremías</a></li>');
if(libro == 'Lm') document.write('<li><b>Lamentaciones</b></li>');
else document.write('<li><a href="../31_lm/c001.html">Lamentaciones</a></li>');
if(libro == 'Ba') document.write('<li><b>Baruc</b></li>');
else document.write('<li><a href="../32_ba/c001.html">Baruc</a></li>');
if(libro == 'Ez') document.write('<li><b>Ezequiel</b></li>');
else document.write('<li><a href="../33_ez/c001.html">Ezequiel</a></li>');
if(libro == 'Dn') document.write('<li><b>Daniel</b></li>');
else document.write('<li><a href="../34_dn/c001.html">Daniel</a></li>');
if(libro == 'Os') document.write('<li><b>Oseas</b></li>');
else document.write('<li><a href="../35_os/c001.html">Oseas</a></li>');
if(libro == 'Jl') document.write('<li><b>Joel</b></li>');
else document.write('<li><a href="../36_jl/c001.html">Joel</a></li>');
if(libro == 'Am') document.write('<li><b>Amós</b></li>');
else document.write('<li><a href="../37_am/c001.html">Amós</a></li>');
if(libro == 'Ab') document.write('<li><b>Abdías</b></li>');
else document.write('<li><a href="../38_ab/c001.html">Abdías</a></li>');
if(libro == 'Jon') document.write('<li><b>Jonás</b></li>');
else document.write('<li><a href="../39_jon/c001.html">Jonás</a></li>');
if(libro == 'Mi') document.write('<li><b>Miqueas</b></li>');
else document.write('<li><a href="../40_mi/c001.html">Miqueas</a></li>');
if(libro == 'Na') document.write('<li><b>Nahún</b></li>');
else document.write('<li><a href="../41_na/c001.html">Nahún</a></li>');
if(libro == 'Ha') document.write('<li><b>Habacuc</b></li>');
else document.write('<li><a href="../42_ha/c001.html">Habacuc</a></li>');
if(libro == 'So') document.write('<li><b>Sofonías</b></li>');
else document.write('<li><a href="../43_so/c001.html">Sofonías</a></li>');
if(libro == 'Ag') document.write('<li><b>Ageo</b></li>');
else document.write('<li><a href="../44_ag/c001.html">Ageo</a></li>');
if(libro == 'Za') document.write('<li><b>Zacarías</b></li>');
else document.write('<li><a href="../45_za/c001.html">Zacarías</a></li>');
if(libro == 'Ml') document.write('<li><b>Malaquías</b></li>');
else document.write('<li><a href="../46_ml/c001.html">Malaquías</a></li>');
document.write('</ul><br /><i>Nuevo Testamento</i><br /><ul>');	
if(libro == 'Mt') document.write('<li><b>Mateo</b></li>');
else document.write('<li><a href="../47_mt/c001.html">Mateo</a></li>');
if(libro == 'Mc') document.write('<li><b>Marcos</b></li>');
else document.write('<li><a href="../48_mc/c001.html">Marcos</a></li>');
if(libro == 'Lc') document.write('<li><b>Lucas</b></li>');
else document.write('<li><a href="../49_lc/c001.html">Lucas</a></li>');
if(libro == 'Jn') document.write('<li><b>Juan</b></li>');
else document.write('<li><a href="../50_jn/c001.html">Juan</a></li>');
if(libro == 'Hch') document.write('<li><b>Hechos</b></li>');
else document.write('<li><a href="../51_hch/c001.html">Hechos</a></li>');
if(libro == 'Rm') document.write('<li><b>Romanos</b></li>');
else document.write('<li><a href="../52_rm/c001.html">Romanos</a></li>');
if(libro == '1Co') document.write('<li><b>I Corintios</b></li>');
else document.write('<li><a href="../53_1co/c001.html">I Corintios</a></li>');
if(libro == '2Co') document.write('<li><b>II Corintios</b></li>');
else document.write('<li><a href="../54_2co/c001.html">II Corintios</a></li>');
if(libro == 'Ga') document.write('<li><b>Gálatas</b></li>');
else document.write('<li><a href="../55_ga/c001.html">Gálatas</a></li>');
if(libro == 'Ef') document.write('<li><b>Efesios</b></li>');
else document.write('<li><a href="../56_ef/c001.html">Efesios</a></li>');
if(libro == 'Flp') document.write('<li><b>Filipenses</b></li>');
else document.write('<li><a href="../57_flp/c001.html">Filipenses</a></li>');
if(libro == 'Col') document.write('<li><b>Colosenses</b></li>');
else document.write('<li><a href="../58_col/c001.html">Colosenses</a></li>');
if(libro == '1Ts') document.write('<li><b>I Tesalonicenses</b></li>');
else document.write('<li><a href="../59_1ts/c001.html">I Tesalonicenses</a></li>');
if(libro == '2Ts') document.write('<li><b>II Tesalonicenses</b></li>');
else document.write('<li><a href="../60_2ts/c001.html">II Tesalonicenses</a></li>');
if(libro == '1Tm') document.write('<li><b>I Timoteo</b></li>');
else document.write('<li><a href="../61_1tm/c001.html">I Timoteo</a></li>');
if(libro == '2Tm') document.write('<li><b>II Timoteo</b></li>');
else document.write('<li><a href="../62_2tm/c001.html">II Timoteo</a></li>');
if(libro == 'Tt') document.write('<li><b>Tito</b></li>');
else document.write('<li><a href="../63_tt/c001.html">Tito</a></li>');
if(libro == 'Flm') document.write('<li><b>Filemón</b></li>');
else document.write('<li><a href="../64_flm/c001.html">Filemón</a></li>');
if(libro == 'Hb') document.write('<li><b>Hebreos</b></li>');
else document.write('<li><a href="../65_hb/c001.html">Hebreos</a></li>');
if(libro == 'St') document.write('<li><b>Santiago</b></li>');
else document.write('<li><a href="../66_st/c001.html">Santiago</a></li>');
if(libro == '1P') document.write('<li><b>I Pedro</b></li>');
else document.write('<li><a href="../67_1p/c001.html">I Pedro</a></li>');
if(libro == '2P') document.write('<li><b>II Pedro</b></li>');
else document.write('<li><a href="../68_2p/c001.html">II Pedro</a></li>');
if(libro == '1Jn') document.write('<li><b>I Juan</b></li>');
else document.write('<li><a href="../69_1jn/c001.html">I Juan</a></li>');
if(libro == '2Jn') document.write('<li><b>II Juan</b></li>');
else document.write('<li><a href="../70_2jn/c001.html">II Juan</a></li>');
if(libro == '3Jn') document.write('<li><b>III Juan</b></li>');
else document.write('<li><a href="../71_3jn/c001.html">III Juan</a></li>');
if(libro == 'Judas') document.write('<li><b>Judas</b></li>');
else document.write('<li><a href="../72_judas/c001.html">Judas</a></li>');
if(libro == 'Ap') document.write('<li><b>Apocalipsis</b></li>');
else document.write('<li><a href="../73_ap/c001.html">Apocalipsis</a></li>');
document.write('</ul></div>');
}

// para los ladri de encuentra.com
function frame_breaker() { 
//if (top != self) { top.location.href = location.href; } 
} 
