const year = new Date().getFullYear(); // Obtiene el año actual
// const year = 2025; // Si prefieres un año fijo

// Lista de audios con su información
const audios = [
    // DIA DE LOS SANTOS
    { nombre: "Santa María, Madre de Dios", 			archivo: "/salterios/src/evan/dias/01enero.mp3",		fecha: `${year}-01-01` }, // 1ro de Enero, Santa Maria Madre de Dios
    { nombre: "2 de Enero", 							archivo: "/salterios/src/evan/dias/02enero.mp3",		fecha: `${year}-01-02` }, // 2 de Enero Santisimo Nombre de nuestro Señor Jesucristo
    { nombre: "3 de Enero", 							archivo: "/salterios/src/evan/dias/03enero.mp3",		fecha: `${year}-01-03` }, // 3 de Enero Santisimo Nombre de nuestro Señor Jesucristo
    { nombre: "La Epifanía del Señor", 					archivo: "/salterios/src/evan/dias/06enero.mp3",		fecha: `${year}-01-06` }, // 6 de Enero, Epifanía del Señor
/*
    { nombre: "Día de la Altagracia", 					archivo: "/salterios/src/evan/dias/21enero.mp3",		fecha: `${year}-01-21` }, // 21 de Enero, Día de la Altagracia
    { nombre: "La Conversión de San Pablo, apóstol",	archivo: "/salterios/src/evan/dias/26enero.mp3",		fecha: `${year}-01-25` }, // 25 La Conversión de San Pablo, apóstol
	*/


/*	Enero		* /	{ nombre: "Tiempo Navidad, Semana 1 Jueves",		archivo: "/salterios/src/evan/tn/1/jueves.mp3",		fecha: `${year}-01-1` },	*/
/*	Enero		* /	{ nombre: "Tiempo Navidad, Semana 1 Viernes",		archivo: "/salterios/src/evan/tn/1/viernes.mp3",	fecha: `${year}-01-2` },	*/
/*	Enero		* /	{ nombre: "Tiempo Navidad, Semana 1 Sabado",		archivo: "/salterios/src/evan/tn/1/sabado.mp3",		fecha: `${year}-01-3` },	*/
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 2 Domingo",		archivo: "/salterios/src/evan/tn/2/domingo.mp3",	fecha: `${year}-01-4` },
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 2 Lunes",			archivo: "/salterios/src/evan/tn/2/lunes.mp3",		fecha: `${year}-01-5` },
/*	Enero		* /	{ nombre: "Tiempo Epifania, Semana 2 Martes",		archivo: "/salterios/src/evan/te/2/martes.mp3",		fecha: `${year}-01-6` },	*/
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Miercoles",	archivo: "/salterios/src/evan/te/2/miercoles.mp3",	fecha: `${year}-01-7` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Jueves",		archivo: "/salterios/src/evan/te/2/jueves.mp3",		fecha: `${year}-01-8` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Viernes",		archivo: "/salterios/src/evan/te/2/viernes.mp3",	fecha: `${year}-01-9` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Sabado",		archivo: "/salterios/src/evan/te/2/sabado.mp3",		fecha: `${year}-01-10` },
/*		*/	
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Domingo",		archivo: "/salterios/src/evan/to/1/domingo.mp3",	fecha: `${year}-01-12` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Lunes",		archivo: "/salterios/src/evan/to/1/lunes.mp3",		fecha: `${year}-01-13` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Martes",		archivo: "/salterios/src/evan/to/1/martes.mp3",		fecha: `${year}-01-14` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Miercoles",	archivo: "/salterios/src/evan/to/1/miercoles.mp3",	fecha: `${year}-01-15` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Jueves",		archivo: "/salterios/src/evan/to/1/jueves.mp3",		fecha: `${year}-01-16` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Viernes", 	archivo: "/salterios/src/evan/to/1/viernes.mp3",	fecha: `${year}-01-17` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Sabado", 		archivo: "/salterios/src/evan/to/1/sabado.mp3",		fecha: `${year}-01-18` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Domingo", 	archivo: "/salterios/src/evan/to/2/domingo.mp3",	fecha: `${year}-01-19` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Lunes", 		archivo: "/salterios/src/evan/to/2/lunes.mp3",		fecha: `${year}-01-20` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Martes", 		archivo: "/salterios/src/evan/to/2/martes.mp3",		fecha: `${year}-01-21` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Miercoles", 	archivo: "/salterios/src/evan/to/2/miercoles.mp3",	fecha: `${year}-01-22` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Jueves", 		archivo: "/salterios/src/evan/to/2/jueves.mp3",		fecha: `${year}-01-23` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Viernes", 	archivo: "/salterios/src/evan/to/2/viernes.mp3",	fecha: `${year}-01-24` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Sabado", 		archivo: "/salterios/src/evan/to/2/sabado.mp3",		fecha: `${year}-01-25` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Domingo", 	archivo: "/salterios/src/evan/to/3/domingo.mp3",	fecha: `${year}-01-26` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Lunes", 		archivo: "/salterios/src/evan/to/3/lunes.mp3",		fecha: `${year}-01-27` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Martes", 		archivo: "/salterios/src/evan/to/3/martes.mp3",		fecha: `${year}-01-28` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Miercoles",	archivo: "/salterios/src/evan/to/3/miercoles.mp3",	fecha: `${year}-01-29` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Jueves",		archivo: "/salterios/src/evan/to/3/jueves.mp3",		fecha: `${year}-01-30` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Viernes",		archivo: "/salterios/src/evan/to/3/viernes.mp3",	fecha: `${year}-01-31` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Sabado",		archivo: "/salterios/src/evan/to/3/sabado.mp3",		fecha: `${year}-02-1` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Domingo",		archivo: "/salterios/src/evan/to/4/domingo.mp3",	fecha: `${year}-02-2` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Lunes",		archivo: "/salterios/src/evan/to/4/lunes.mp3",		fecha: `${year}-02-3` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Martes",		archivo: "/salterios/src/evan/to/4/martes.mp3",		fecha: `${year}-02-4` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Miercoles",	archivo: "/salterios/src/evan/to/4/miercoles.mp3",	fecha: `${year}-02-5` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Jueves",		archivo: "/salterios/src/evan/to/4/jueves.mp3",		fecha: `${year}-02-6` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Viernes",		archivo: "/salterios/src/evan/to/4/viernes.mp3",	fecha: `${year}-02-7` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Sabado",		archivo: "/salterios/src/evan/to/4/sabado.mp3",		fecha: `${year}-02-8` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Domingo",		archivo: "/salterios/src/evan/to/5/domingo.mp3",	fecha: `${year}-02-9` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Lunes",		archivo: "/salterios/src/evan/to/5/lunes.mp3",		fecha: `${year}-02-10` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Martes",		archivo: "/salterios/src/evan/to/5/martes.mp3",		fecha: `${year}-02-11` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Miercoles",	archivo: "/salterios/src/evan/to/5/miercoles.mp3",	fecha: `${year}-02-12` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Jueves",		archivo: "/salterios/src/evan/to/5/jueves.mp3",		fecha: `${year}-02-13` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Viernes",		archivo: "/salterios/src/evan/to/5/viernes.mp3",	fecha: `${year}-02-14` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Sabado",		archivo: "/salterios/src/evan/to/5/sabado.mp3",		fecha: `${year}-02-15` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Domingo",		archivo: "/salterios/src/evan/to/6/domingo.mp3",	fecha: `${year}-02-16` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Lunes",		archivo: "/salterios/src/evan/to/6/lunes.mp3",		fecha: `${year}-02-17` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Martes",		archivo: "/salterios/src/evan/to/6/martes.mp3",		fecha: `${year}-02-18` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Miercoles",	archivo: "/salterios/src/evan/to/6/miercoles.mp3",	fecha: `${year}-02-19` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Jueves",		archivo: "/salterios/src/evan/to/6/jueves.mp3",		fecha: `${year}-02-20` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Viernes",		archivo: "/salterios/src/evan/to/6/viernes.mp3",	fecha: `${year}-02-21` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Sabado",		archivo: "/salterios/src/evan/to/6/sabado.mp3",		fecha: `${year}-02-22` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Domingo",		archivo: "/salterios/src/evan/to/7/domingo.mp3",	fecha: `${year}-02-23` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Lunes",		archivo: "/salterios/src/evan/to/7/lunes.mp3",		fecha: `${year}-02-24` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Martes",		archivo: "/salterios/src/evan/to/7/martes.mp3",		fecha: `${year}-02-25` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Miercoles",	archivo: "/salterios/src/evan/to/7/miercoles.mp3",	fecha: `${year}-02-26` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Jueves",		archivo: "/salterios/src/evan/to/7/jueves.mp3",		fecha: `${year}-02-27` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Viernes",		archivo: "/salterios/src/evan/to/7/viernes.mp3",	fecha: `${year}-02-28` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 7 Sabado",		archivo: "/salterios/src/evan/to/7/sabado.mp3",		fecha: `${year}-03-1` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Domingo",		archivo: "/salterios/src/evan/to/8/domingo.mp3",	fecha: `${year}-03-2` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Lunes",		archivo: "/salterios/src/evan/to/8/lunes.mp3",		fecha: `${year}-03-3` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Martes",		archivo: "/salterios/src/evan/to/8/martes.mp3",		fecha: `${year}-03-4` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Miercoles Ceniza",		archivo: "/salterios/src/evan/tc/cnz/miercoles.mp3",fecha: `${year}-03-5` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Jueves",		archivo: "/salterios/src/evan/tc/cnz/jueves.mp3",	fecha: `${year}-03-6` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Viernes",		archivo: "/salterios/src/evan/tc/cnz/viernes.mp3",	fecha: `${year}-03-7` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Sabado",		archivo: "/salterios/src/evan/tc/cnz/sabado.mp3",	fecha: `${year}-03-8` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Domingo",		archivo: "/salterios/src/evan/tc/1/domingo.mp3",	fecha: `${year}-03-9` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Lunes",		archivo: "/salterios/src/evan/tc/1/lunes.mp3",		fecha: `${year}-03-10` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Martes",		archivo: "/salterios/src/evan/tc/1/martes.mp3",		fecha: `${year}-03-11` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Miercoles",	archivo: "/salterios/src/evan/tc/1/miercoles.mp3",	fecha: `${year}-03-12` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Jueves",		archivo: "/salterios/src/evan/tc/1/jueves.mp3",		fecha: `${year}-03-13` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Viernes",		archivo: "/salterios/src/evan/tc/1/viernes.mp3",	fecha: `${year}-03-14` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Sabado",		archivo: "/salterios/src/evan/tc/1/sabado.mp3",		fecha: `${year}-03-15` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Domingo",		archivo: "/salterios/src/evan/tc/2/domingo.mp3",	fecha: `${year}-03-16` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Lunes",		archivo: "/salterios/src/evan/tc/2/lunes.mp3",		fecha: `${year}-03-17` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Martes",		archivo: "/salterios/src/evan/tc/2/martes.mp3",		fecha: `${year}-03-18` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Miercoles",	archivo: "/salterios/src/evan/tc/2/miercoles.mp3",	fecha: `${year}-03-19` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Jueves",		archivo: "/salterios/src/evan/tc/2/jueves.mp3",		fecha: `${year}-03-20` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Viernes",		archivo: "/salterios/src/evan/tc/2/viernes.mp3",	fecha: `${year}-03-21` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Sabado",		archivo: "/salterios/src/evan/tc/2/sabado.mp3",		fecha: `${year}-03-22` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Domingo",		archivo: "/salterios/src/evan/tc/3/domingo.mp3",	fecha: `${year}-03-23` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Lunes",		archivo: "/salterios/src/evan/tc/3/lunes.mp3",		fecha: `${year}-03-24` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Martes",		archivo: "/salterios/src/evan/tc/3/martes.mp3",		fecha: `${year}-03-25` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Miercoles",	archivo: "/salterios/src/evan/tc/3/miercoles.mp3",	fecha: `${year}-03-26` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Jueves",		archivo: "/salterios/src/evan/tc/3/jueves.mp3",		fecha: `${year}-03-27` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Viernes",		archivo: "/salterios/src/evan/tc/3/viernes.mp3",	fecha: `${year}-03-28` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Sabado",		archivo: "/salterios/src/evan/tc/3/sabado.mp3",		fecha: `${year}-03-29` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Domingo",		archivo: "/salterios/src/evan/tc/4/domingo.mp3",	fecha: `${year}-03-30` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Lunes",		archivo: "/salterios/src/evan/tc/4/lunes.mp3",		fecha: `${year}-03-31` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Martes",		archivo: "/salterios/src/evan/tc/4/martes.mp3",		fecha: `${year}-04-1` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Miercoles",	archivo: "/salterios/src/evan/tc/4/miercoles.mp3",	fecha: `${year}-04-2` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Jueves",		archivo: "/salterios/src/evan/tc/4/jueves.mp3",		fecha: `${year}-04-3` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Viernes",		archivo: "/salterios/src/evan/tc/4/viernes.mp3",	fecha: `${year}-04-4` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Sabado",		archivo: "/salterios/src/evan/tc/4/sabado.mp3",		fecha: `${year}-04-5` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Domingo",		archivo: "/salterios/src/evan/tc/5/domingo.mp3",	fecha: `${year}-04-6` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Lunes",		archivo: "/salterios/src/evan/tc/5/lunes.mp3",		fecha: `${year}-04-7` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Martes",		archivo: "/salterios/src/evan/tc/5/martes.mp3",		fecha: `${year}-04-8` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Miercoles",	archivo: "/salterios/src/evan/tc/5/miercoles.mp3",	fecha: `${year}-04-9` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Jueves",		archivo: "/salterios/src/evan/tc/5/jueves.mp3",		fecha: `${year}-04-10` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Viernes",		archivo: "/salterios/src/evan/tc/5/viernes.mp3",	fecha: `${year}-04-11` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Sabado",		archivo: "/salterios/src/evan/tc/5/sabado.mp3",		fecha: `${year}-04-12` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Domingo De Ramos",		archivo: "/salterios/src/evan/tc/6/domingo.mp3",	fecha: `${year}-04-13` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Lunes",		archivo: "/salterios/src/evan/tc/6/lunes.mp3",		fecha: `${year}-04-14` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Martes",		archivo: "/salterios/src/evan/tc/6/martes.mp3",		fecha: `${year}-04-15` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Miercoles",	archivo: "/salterios/src/evan/tc/6/miercoles.mp3",	fecha: `${year}-04-16` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Jueves",	archivo: "/salterios/src/evan/tc/6/jueves.mp3",		fecha: `${year}-04-17` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Viernes",archivo: "/salterios/src/evan/tc/6/viernes.mp3",	fecha: `${year}-04-18` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Sabado",	archivo: "/salterios/src/evan/tc/6/sabado.mp3",		fecha: `${year}-04-19` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Domingo",		archivo: "/salterios/src/evan/tp/1/domingo.mp3",	fecha: `${year}-04-20` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Lunes",			archivo: "/salterios/src/evan/tp/1/lunes.mp3",		fecha: `${year}-04-21` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Martes",		archivo: "/salterios/src/evan/tp/1/martes.mp3",		fecha: `${year}-04-22` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Miercoles",		archivo: "/salterios/src/evan/tp/1/miercoles.mp3",	fecha: `${year}-04-23` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Jueves",		archivo: "/salterios/src/evan/tp/1/jueves.mp3",		fecha: `${year}-04-24` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Viernes",		archivo: "/salterios/src/evan/tp/1/viernes.mp3",	fecha: `${year}-04-25` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Sabado",		archivo: "/salterios/src/evan/tp/1/sabado.mp3",		fecha: `${year}-04-26` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Domingo",		archivo: "/salterios/src/evan/tp/2/domingo.mp3",	fecha: `${year}-04-27` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Lunes",			archivo: "/salterios/src/evan/tp/2/lunes.mp3",		fecha: `${year}-04-28` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Martes",		archivo: "/salterios/src/evan/tp/2/martes.mp3",		fecha: `${year}-04-29` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Miercoles",		archivo: "/salterios/src/evan/tp/2/miercoles.mp3",	fecha: `${year}-04-30` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Jueves",		archivo: "/salterios/src/evan/tp/2/jueves.mp3",		fecha: `${year}-05-1` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Viernes",		archivo: "/salterios/src/evan/tp/2/viernes.mp3",	fecha: `${year}-05-2` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Sabado",		archivo: "/salterios/src/evan/tp/2/sabado.mp3",		fecha: `${year}-05-3` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Domingo",		archivo: "/salterios/src/evan/tp/3/domingo.mp3",	fecha: `${year}-05-4` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Lunes",			archivo: "/salterios/src/evan/tp/3/lunes.mp3",		fecha: `${year}-05-5` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Martes",		archivo: "/salterios/src/evan/tp/3/martes.mp3",		fecha: `${year}-05-6` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Miercoles",		archivo: "/salterios/src/evan/tp/3/miercoles.mp3",	fecha: `${year}-05-7` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Jueves",		archivo: "/salterios/src/evan/tp/3/jueves.mp3",		fecha: `${year}-05-8` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Viernes",		archivo: "/salterios/src/evan/tp/3/viernes.mp3",	fecha: `${year}-05-9` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Sabado",		archivo: "/salterios/src/evan/tp/3/sabado.mp3",		fecha: `${year}-05-10` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Domingo",		archivo: "/salterios/src/evan/tp/4/domingo.mp3",	fecha: `${year}-05-11` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Lunes",			archivo: "/salterios/src/evan/tp/4/lunes.mp3",		fecha: `${year}-05-12` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Martes",		archivo: "/salterios/src/evan/tp/4/martes.mp3",		fecha: `${year}-05-13` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Miercoles",		archivo: "/salterios/src/evan/tp/4/miercoles.mp3",	fecha: `${year}-05-14` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Jueves",		archivo: "/salterios/src/evan/tp/4/jueves.mp3",		fecha: `${year}-05-15` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Viernes",		archivo: "/salterios/src/evan/tp/4/viernes.mp3",	fecha: `${year}-05-16` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Sabado",		archivo: "/salterios/src/evan/tp/4/sabado.mp3",		fecha: `${year}-05-17` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Domingo",		archivo: "/salterios/src/evan/tp/5/domingo.mp3",	fecha: `${year}-05-18` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Lunes",			archivo: "/salterios/src/evan/tp/5/lunes.mp3",		fecha: `${year}-05-19` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Martes",		archivo: "/salterios/src/evan/tp/5/martes.mp3",		fecha: `${year}-05-20` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Miercoles",		archivo: "/salterios/src/evan/tp/5/miercoles.mp3",	fecha: `${year}-05-21` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Jueves",		archivo: "/salterios/src/evan/tp/5/jueves.mp3",		fecha: `${year}-05-22` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Viernes",		archivo: "/salterios/src/evan/tp/5/viernes.mp3",	fecha: `${year}-05-23` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Sabado",		archivo: "/salterios/src/evan/tp/5/sabado.mp3",		fecha: `${year}-05-24` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Domingo",		archivo: "/salterios/src/evan/tp/6/domingo.mp3",	fecha: `${year}-05-25` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Lunes",			archivo: "/salterios/src/evan/tp/6/lunes.mp3",		fecha: `${year}-05-26` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Martes",		archivo: "/salterios/src/evan/tp/6/martes.mp3",		fecha: `${year}-05-27` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Miercoles",		archivo: "/salterios/src/evan/tp/6/miercoles.mp3",	fecha: `${year}-05-28` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Jueves",		archivo: "/salterios/src/evan/tp/6/jueves.mp3",		fecha: `${year}-05-29` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Viernes",		archivo: "/salterios/src/evan/tp/6/viernes.mp3",	fecha: `${year}-05-30` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Sabado",		archivo: "/salterios/src/evan/tp/6/sabado.mp3",		fecha: `${year}-05-31` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Domingo",		archivo: "/salterios/src/evan/tp/7/domingo.mp3",	fecha: `${year}-06-1` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Lunes",			archivo: "/salterios/src/evan/tp/7/lunes.mp3",		fecha: `${year}-06-2` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Martes",		archivo: "/salterios/src/evan/tp/7/martes.mp3",		fecha: `${year}-06-3` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Miercoles",		archivo: "/salterios/src/evan/tp/7/miercoles.mp3",	fecha: `${year}-06-4` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Jueves",		archivo: "/salterios/src/evan/tp/7/jueves.mp3",		fecha: `${year}-06-5` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Viernes",		archivo: "/salterios/src/evan/tp/7/viernes.mp3",	fecha: `${year}-06-6` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Sabado",		archivo: "/salterios/src/evan/tp/7/sabado.mp3",		fecha: `${year}-06-7` },
/*	Junio		*/	{ nombre: "Domingo de Pentecostes",					archivo: "/salterios/src/evan/tp/8/pentecostes.mp3",fecha: `${year}-06-8` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Lunes",		archivo: "/salterios/src/evan/to/10/lunes.mp3",		fecha: `${year}-06-9` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Martes",		archivo: "/salterios/src/evan/to/10/martes.mp3",	fecha: `${year}-06-10` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Miercoles",	archivo: "/salterios/src/evan/to/10/miercoles.mp3",	fecha: `${year}-06-11` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Jueves",		archivo: "/salterios/src/evan/to/10/jueves.mp3",	fecha: `${year}-06-12` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Viernes",	archivo: "/salterios/src/evan/to/10/viernes.mp3",	fecha: `${year}-06-13` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Sabado",		archivo: "/salterios/src/evan/to/10/sabado.mp3",	fecha: `${year}-06-14` },
/*	Junio		*/	{ nombre: "La Santísima Trinidad",					archivo: "/salterios/src/evan/tp/8/STrinidad.mp3",	fecha: `${year}-06-15` },
/*	Junio			{ nombre: "La Santísima Trinidad",					archivo: "/salterios/src/evan/to/11/domingo.mp3",	fecha: `${year}-06-15` }, */
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Lunes",		archivo: "/salterios/src/evan/to/11/lunes.mp3",		fecha: `${year}-06-16` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Martes",		archivo: "/salterios/src/evan/to/11/martes.mp3",	fecha: `${year}-06-17` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Miercoles",	archivo: "/salterios/src/evan/to/11/miercoles.mp3",	fecha: `${year}-06-18` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Jueves",		archivo: "/salterios/src/evan/to/11/jueves.mp3",	fecha: `${year}-06-19` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Viernes",	archivo: "/salterios/src/evan/to/11/viernes.mp3",	fecha: `${year}-06-20` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Sabado",		archivo: "/salterios/src/evan/to/11/sabado.mp3",	fecha: `${year}-06-21` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Domingo",	archivo: "/salterios/src/evan/to/12/domingo.mp3",	fecha: `${year}-06-22` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Lunes",		archivo: "/salterios/src/evan/to/12/lunes.mp3",		fecha: `${year}-06-23` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Martes",		archivo: "/salterios/src/evan/to/12/martes.mp3",	fecha: `${year}-06-24` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Miercoles",	archivo: "/salterios/src/evan/to/12/miercoles.mp3",	fecha: `${year}-06-25` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Jueves",		archivo: "/salterios/src/evan/to/12/jueves.mp3",	fecha: `${year}-06-26` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Viernes",	archivo: "/salterios/src/evan/to/12/viernes.mp3",	fecha: `${year}-06-27` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Sabado",		archivo: "/salterios/src/evan/to/12/sabado.mp3",	fecha: `${year}-06-28` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Domingo",	archivo: "/salterios/src/evan/to/13/domingo.mp3",	fecha: `${year}-06-29` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Lunes",		archivo: "/salterios/src/evan/to/13/lunes.mp3",		fecha: `${year}-06-30` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Martes",		archivo: "/salterios/src/evan/to/13/martes.mp3",	fecha: `${year}-07-1` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Miercoles",	archivo: "/salterios/src/evan/to/13/miercoles.mp3",	fecha: `${year}-07-2` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Jueves",		archivo: "/salterios/src/evan/to/13/jueves.mp3",	fecha: `${year}-07-3` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Viernes",	archivo: "/salterios/src/evan/to/13/viernes.mp3",	fecha: `${year}-07-4` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Sabado",		archivo: "/salterios/src/evan/to/13/sabado.mp3",	fecha: `${year}-07-5` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Domingo",	archivo: "/salterios/src/evan/to/14/domingo.mp3",	fecha: `${year}-07-6` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Lunes",		archivo: "/salterios/src/evan/to/14/lunes.mp3",		fecha: `${year}-07-7` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Martes",		archivo: "/salterios/src/evan/to/14/martes.mp3",	fecha: `${year}-07-8` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Miercoles",	archivo: "/salterios/src/evan/to/14/miercoles.mp3",	fecha: `${year}-07-9` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Jueves",		archivo: "/salterios/src/evan/to/14/jueves.mp3",	fecha: `${year}-07-10` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Viernes",	archivo: "/salterios/src/evan/to/14/viernes.mp3",	fecha: `${year}-07-11` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Sabado",		archivo: "/salterios/src/evan/to/14/sabado.mp3",	fecha: `${year}-07-12` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Domingo",	archivo: "/salterios/src/evan/to/15/domingo.mp3",	fecha: `${year}-07-13` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Lunes",		archivo: "/salterios/src/evan/to/15/lunes.mp3",		fecha: `${year}-07-14` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Martes",		archivo: "/salterios/src/evan/to/15/martes.mp3",	fecha: `${year}-07-15` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Miercoles",	archivo: "/salterios/src/evan/to/15/miercoles.mp3",	fecha: `${year}-07-16` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Jueves",		archivo: "/salterios/src/evan/to/15/jueves.mp3",	fecha: `${year}-07-17` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Viernes",	archivo: "/salterios/src/evan/to/15/viernes.mp3",	fecha: `${year}-07-18` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Sabado",		archivo: "/salterios/src/evan/to/15/sabado.mp3",	fecha: `${year}-07-19` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Domingo",	archivo: "/salterios/src/evan/to/16/domingo.mp3",	fecha: `${year}-07-20` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Lunes",		archivo: "/salterios/src/evan/to/16/lunes.mp3",		fecha: `${year}-07-21` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Martes",		archivo: "/salterios/src/evan/to/16/martes.mp3",	fecha: `${year}-07-22` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Miercoles",	archivo: "/salterios/src/evan/to/16/miercoles.mp3",	fecha: `${year}-07-23` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Jueves",		archivo: "/salterios/src/evan/to/16/jueves.mp3",	fecha: `${year}-07-24` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Viernes",	archivo: "/salterios/src/evan/to/16/viernes.mp3",	fecha: `${year}-07-25` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Sabado",		archivo: "/salterios/src/evan/to/16/sabado.mp3",	fecha: `${year}-07-26` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Domingo",	archivo: "/salterios/src/evan/to/17/domingo.mp3",	fecha: `${year}-07-27` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Lunes",		archivo: "/salterios/src/evan/to/17/lunes.mp3",		fecha: `${year}-07-28` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Martes",		archivo: "/salterios/src/evan/to/17/martes.mp3",	fecha: `${year}-07-29` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Miercoles",	archivo: "/salterios/src/evan/to/17/miercoles.mp3",	fecha: `${year}-07-30` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Jueves",		archivo: "/salterios/src/evan/to/17/jueves.mp3",	fecha: `${year}-07-31` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 17 Viernes",	archivo: "/salterios/src/evan/to/17/viernes.mp3",	fecha: `${year}-08-1` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 17 Sabado",		archivo: "/salterios/src/evan/to/17/sabado.mp3",	fecha: `${year}-08-2` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Domingo",	archivo: "/salterios/src/evan/to/18/domingo.mp3",	fecha: `${year}-08-3` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Lunes",		archivo: "/salterios/src/evan/to/18/lunes.mp3",		fecha: `${year}-08-4` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Martes",		archivo: "/salterios/src/evan/to/18/martes.mp3",	fecha: `${year}-08-5` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Miercoles",	archivo: "/salterios/src/evan/to/18/miercoles.mp3",	fecha: `${year}-08-6` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Jueves",		archivo: "/salterios/src/evan/to/18/jueves.mp3",	fecha: `${year}-08-7` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Viernes",	archivo: "/salterios/src/evan/to/18/viernes.mp3",	fecha: `${year}-08-8` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Sabado",		archivo: "/salterios/src/evan/to/18/sabado.mp3",	fecha: `${year}-08-9` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Domingo",	archivo: "/salterios/src/evan/to/19/domingo.mp3",	fecha: `${year}-08-10` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Lunes",		archivo: "/salterios/src/evan/to/19/lunes.mp3",		fecha: `${year}-08-11` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Martes",		archivo: "/salterios/src/evan/to/19/martes.mp3",	fecha: `${year}-08-12` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Miercoles",	archivo: "/salterios/src/evan/to/19/miercoles.mp3",	fecha: `${year}-08-13` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Jueves",		archivo: "/salterios/src/evan/to/19/jueves.mp3",	fecha: `${year}-08-14` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Viernes",	archivo: "/salterios/src/evan/to/19/viernes.mp3",	fecha: `${year}-08-15` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Sabado",		archivo: "/salterios/src/evan/to/19/sabado.mp3",	fecha: `${year}-08-16` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Domingo",	archivo: "/salterios/src/evan/to/20/domingo.mp3",	fecha: `${year}-08-17` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Lunes",		archivo: "/salterios/src/evan/to/20/lunes.mp3",		fecha: `${year}-08-18` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Martes",		archivo: "/salterios/src/evan/to/20/martes.mp3",	fecha: `${year}-08-19` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Miercoles",	archivo: "/salterios/src/evan/to/20/miercoles.mp3",	fecha: `${year}-08-20` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Jueves",		archivo: "/salterios/src/evan/to/20/jueves.mp3",	fecha: `${year}-08-21` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Viernes",	archivo: "/salterios/src/evan/to/20/viernes.mp3",	fecha: `${year}-08-22` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Sabado",		archivo: "/salterios/src/evan/to/20/sabado.mp3",	fecha: `${year}-08-23` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Domingo",	archivo: "/salterios/src/evan/to/21/domingo.mp3",	fecha: `${year}-08-24` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Lunes",		archivo: "/salterios/src/evan/to/21/lunes.mp3",		fecha: `${year}-08-25` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Martes",		archivo: "/salterios/src/evan/to/21/martes.mp3",	fecha: `${year}-08-26` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Miercoles",	archivo: "/salterios/src/evan/to/21/miercoles.mp3",	fecha: `${year}-08-27` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Jueves",		archivo: "/salterios/src/evan/to/21/jueves.mp3",	fecha: `${year}-08-28` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Viernes",	archivo: "/salterios/src/evan/to/21/viernes.mp3",	fecha: `${year}-08-29` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Sabado",		archivo: "/salterios/src/evan/to/21/sabado.mp3",	fecha: `${year}-08-30` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 22 Domingo",	archivo: "/salterios/src/evan/to/22/domingo.mp3",	fecha: `${year}-08-31` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Lunes",		archivo: "/salterios/src/evan/to/22/lunes.mp3",		fecha: `${year}-09-1` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Martes",		archivo: "/salterios/src/evan/to/22/martes.mp3",	fecha: `${year}-09-2` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Miercoles",	archivo: "/salterios/src/evan/to/22/miercoles.mp3",	fecha: `${year}-09-3` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Jueves",		archivo: "/salterios/src/evan/to/22/jueves.mp3",	fecha: `${year}-09-4` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Viernes",	archivo: "/salterios/src/evan/to/22/viernes.mp3",	fecha: `${year}-09-5` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Sabado",		archivo: "/salterios/src/evan/to/22/sabado.mp3",	fecha: `${year}-09-6` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Domingo",	archivo: "/salterios/src/evan/to/23/domingo.mp3",	fecha: `${year}-09-7` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Lunes",		archivo: "/salterios/src/evan/to/23/lunes.mp3",		fecha: `${year}-09-8` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Martes",		archivo: "/salterios/src/evan/to/23/martes.mp3",	fecha: `${year}-09-9` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Miercoles",	archivo: "/salterios/src/evan/to/23/miercoles.mp3",	fecha: `${year}-09-10` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Jueves",		archivo: "/salterios/src/evan/to/23/jueves.mp3",	fecha: `${year}-09-11` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Viernes",	archivo: "/salterios/src/evan/to/23/viernes.mp3",	fecha: `${year}-09-12` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Sabado",		archivo: "/salterios/src/evan/to/23/sabado.mp3",	fecha: `${year}-09-13` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Domingo",	archivo: "/salterios/src/evan/to/24/domingo.mp3",	fecha: `${year}-09-14` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Lunes",		archivo: "/salterios/src/evan/to/24/lunes.mp3",		fecha: `${year}-09-15` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Martes",		archivo: "/salterios/src/evan/to/24/martes.mp3",	fecha: `${year}-09-16` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Miercoles",	archivo: "/salterios/src/evan/to/24/miercoles.mp3",	fecha: `${year}-09-17` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Jueves",		archivo: "/salterios/src/evan/to/24/jueves.mp3",	fecha: `${year}-09-18` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Viernes",	archivo: "/salterios/src/evan/to/24/viernes.mp3",	fecha: `${year}-09-19` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Sabado",		archivo: "/salterios/src/evan/to/24/sabado.mp3",	fecha: `${year}-09-20` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Domingo",	archivo: "/salterios/src/evan/to/25/domingo.mp3",	fecha: `${year}-09-21` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Lunes",		archivo: "/salterios/src/evan/to/25/lunes.mp3",		fecha: `${year}-09-22` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Martes",		archivo: "/salterios/src/evan/to/25/martes.mp3",	fecha: `${year}-09-23` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Miercoles",	archivo: "/salterios/src/evan/to/25/miercoles.mp3",	fecha: `${year}-09-24` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Jueves",		archivo: "/salterios/src/evan/to/25/jueves.mp3",	fecha: `${year}-09-25` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Viernes",	archivo: "/salterios/src/evan/to/25/viernes.mp3",	fecha: `${year}-09-26` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Sabado",		archivo: "/salterios/src/evan/to/25/sabado.mp3",	fecha: `${year}-09-27` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Domingo",	archivo: "/salterios/src/evan/to/26/domingo.mp3",	fecha: `${year}-09-28` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Lunes",		archivo: "/salterios/src/evan/to/26/lunes.mp3",		fecha: `${year}-09-29` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Martes",		archivo: "/salterios/src/evan/to/26/martes.mp3",	fecha: `${year}-09-30` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 26 Miercoles",	archivo: "/salterios/src/evan/to/26/miercoles.mp3",	fecha: `${year}-10-1` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 26 Jueves",		archivo: "/salterios/src/evan/to/26/jueves.mp3",	fecha: `${year}-10-2` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 26 Viernes",	archivo: "/salterios/src/evan/to/26/viernes.mp3",	fecha: `${year}-10-3` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 26 Sabado",		archivo: "/salterios/src/evan/to/26/sabado.mp3",	fecha: `${year}-10-4` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Domingo",	archivo: "/salterios/src/evan/to/27/domingo.mp3",	fecha: `${year}-10-5` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Lunes",		archivo: "/salterios/src/evan/to/27/lunes.mp3",		fecha: `${year}-10-6` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Martes",		archivo: "/salterios/src/evan/to/27/martes.mp3",	fecha: `${year}-10-7` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Miercoles",	archivo: "/salterios/src/evan/to/27/miercoles.mp3",	fecha: `${year}-10-8` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Jueves",		archivo: "/salterios/src/evan/to/27/jueves.mp3",	fecha: `${year}-10-9` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Viernes",	archivo: "/salterios/src/evan/to/27/viernes.mp3",	fecha: `${year}-10-10` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 27 Sabado",		archivo: "/salterios/src/evan/to/27/sabado.mp3",	fecha: `${year}-10-11` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Domingo",	archivo: "/salterios/src/evan/to/28/domingo.mp3",	fecha: `${year}-10-12` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Lunes",		archivo: "/salterios/src/evan/to/28/lunes.mp3",		fecha: `${year}-10-13` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Martes",		archivo: "/salterios/src/evan/to/28/martes.mp3",	fecha: `${year}-10-14` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Miercoles",	archivo: "/salterios/src/evan/to/28/miercoles.mp3",	fecha: `${year}-10-15` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Jueves",		archivo: "/salterios/src/evan/to/28/jueves.mp3",	fecha: `${year}-10-16` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Viernes",	archivo: "/salterios/src/evan/to/28/viernes.mp3",	fecha: `${year}-10-17` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 28 Sabado",		archivo: "/salterios/src/evan/to/28/sabado.mp3",	fecha: `${year}-10-18` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Domingo",	archivo: "/salterios/src/evan/to/29/domingo.mp3",	fecha: `${year}-10-19` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Lunes",		archivo: "/salterios/src/evan/to/29/lunes.mp3",		fecha: `${year}-10-20` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Martes",		archivo: "/salterios/src/evan/to/29/martes.mp3",	fecha: `${year}-10-21` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Miercoles",	archivo: "/salterios/src/evan/to/29/miercoles.mp3",	fecha: `${year}-10-22` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Jueves",		archivo: "/salterios/src/evan/to/29/jueves.mp3",	fecha: `${year}-10-23` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Viernes",	archivo: "/salterios/src/evan/to/29/viernes.mp3",	fecha: `${year}-10-24` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 29 Sabado",		archivo: "/salterios/src/evan/to/29/sabado.mp3",	fecha: `${year}-10-25` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Domingo",	archivo: "/salterios/src/evan/to/30/domingo.mp3",	fecha: `${year}-10-26` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Lunes",		archivo: "/salterios/src/evan/to/30/lunes.mp3",		fecha: `${year}-10-27` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Martes",		archivo: "/salterios/src/evan/to/30/martes.mp3",	fecha: `${year}-10-28` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Miercoles",	archivo: "/salterios/src/evan/to/30/miercoles.mp3",	fecha: `${year}-10-29` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Jueves",		archivo: "/salterios/src/evan/to/30/jueves.mp3",	fecha: `${year}-10-30` },
/*	Octubre		*/	{ nombre: "Tiempo Ordinario, Semana 30 Viernes",	archivo: "/salterios/src/evan/to/30/viernes.mp3",	fecha: `${year}-10-31` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Sabado",		archivo: "/salterios/src/evan/to/30/sabado.mp3",	fecha: `${year}-11-1` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Domingo",	archivo: "/salterios/src/evan/to/31/domingo.mp3",	fecha: `${year}-11-2` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Lunes",		archivo: "/salterios/src/evan/to/31/lunes.mp3",		fecha: `${year}-11-3` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Martes",		archivo: "/salterios/src/evan/to/31/martes.mp3",	fecha: `${year}-11-4` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Miercoles",	archivo: "/salterios/src/evan/to/31/miercoles.mp3",	fecha: `${year}-11-5` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Jueves",		archivo: "/salterios/src/evan/to/31/jueves.mp3",	fecha: `${year}-11-6` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Viernes",	archivo: "/salterios/src/evan/to/31/viernes.mp3",	fecha: `${year}-11-7` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Sabado",		archivo: "/salterios/src/evan/to/31/sabado.mp3",	fecha: `${year}-11-8` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Domingo",	archivo: "/salterios/src/evan/to/32/domingo.mp3",	fecha: `${year}-11-9` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Lunes",		archivo: "/salterios/src/evan/to/32/lunes.mp3",		fecha: `${year}-11-10` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Martes",		archivo: "/salterios/src/evan/to/32/martes.mp3",	fecha: `${year}-11-11` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Miercoles",	archivo: "/salterios/src/evan/to/32/miercoles.mp3",	fecha: `${year}-11-12` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Jueves",		archivo: "/salterios/src/evan/to/32/jueves.mp3",	fecha: `${year}-11-13` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Viernes",	archivo: "/salterios/src/evan/to/32/viernes.mp3",	fecha: `${year}-11-14` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Sabado",		archivo: "/salterios/src/evan/to/32/sabado.mp3",	fecha: `${year}-11-15` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Domingo",	archivo: "/salterios/src/evan/to/33/domingo.mp3",	fecha: `${year}-11-16` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Lunes",		archivo: "/salterios/src/evan/to/33/lunes.mp3",		fecha: `${year}-11-17` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Martes",		archivo: "/salterios/src/evan/to/33/martes.mp3",	fecha: `${year}-11-18` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Miercoles",	archivo: "/salterios/src/evan/to/33/miercoles.mp3",	fecha: `${year}-11-19` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Jueves",		archivo: "/salterios/src/evan/to/33/jueves.mp3",	fecha: `${year}-11-20` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Viernes",	archivo: "/salterios/src/evan/to/33/viernes.mp3",	fecha: `${year}-11-21` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Sabado",		archivo: "/salterios/src/evan/to/33/sabado.mp3",	fecha: `${year}-11-22` },
/*	Noviembre	*/	{ nombre: "Cristo Rey, Domingo de la Semana 34",	archivo: "/salterios/src/evan/to/34/domingo.mp3",	fecha: `${year}-11-23` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Lunes",		archivo: "/salterios/src/evan/to/34/lunes.mp3",		fecha: `${year}-11-24` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Martes",		archivo: "/salterios/src/evan/to/34/martes.mp3",	fecha: `${year}-11-25` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Miercoles",	archivo: "/salterios/src/evan/to/34/miercoles.mp3",	fecha: `${year}-11-26` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Jueves",		archivo: "/salterios/src/evan/to/34/jueves.mp3",	fecha: `${year}-11-27` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Viernes",	archivo: "/salterios/src/evan/to/34/viernes.mp3",	fecha: `${year}-11-28` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Sabado",		archivo: "/salterios/src/evan/to/34/sabado.mp3",	fecha: `${year}-11-29` },
/*	Noviembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Domingo",		archivo: "/salterios/src/evan/ta/1/domingo.mp3",	fecha: `${year}-11-30` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Lunes",		archivo: "/salterios/src/evan/ta/1/lunes.mp3",		fecha: `${year}-12-1` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Martes",		archivo: "/salterios/src/evan/ta/1/martes.mp3",		fecha: `${year}-12-2` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Miercoles",	archivo: "/salterios/src/evan/ta/1/miercoles.mp3",	fecha: `${year}-12-3` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Jueves",		archivo: "/salterios/src/evan/ta/1/jueves.mp3",		fecha: `${year}-12-4` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Viernes",		archivo: "/salterios/src/evan/ta/1/viernes.mp3",	fecha: `${year}-12-5` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Sabado",		archivo: "/salterios/src/evan/ta/1/sabado.mp3",		fecha: `${year}-12-6` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Domingo",		archivo: "/salterios/src/evan/ta/2/domingo.mp3",	fecha: `${year}-12-7` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Lunes",		archivo: "/salterios/src/evan/ta/2/lunes.mp3",		fecha: `${year}-12-8` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Martes",		archivo: "/salterios/src/evan/ta/2/martes.mp3",		fecha: `${year}-12-9` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Miercoles",	archivo: "/salterios/src/evan/ta/2/miercoles.mp3",	fecha: `${year}-12-10` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Jueves",		archivo: "/salterios/src/evan/ta/2/jueves.mp3",		fecha: `${year}-12-11` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Viernes",		archivo: "/salterios/src/evan/ta/2/viernes.mp3",	fecha: `${year}-12-12` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Sabado",		archivo: "/salterios/src/evan/ta/2/sabado.mp3",		fecha: `${year}-12-13` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Domingo",		archivo: "/salterios/src/evan/ta/3/domingo.mp3",	fecha: `${year}-12-14` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Lunes",		archivo: "/salterios/src/evan/ta/3/lunes.mp3",		fecha: `${year}-12-15` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Martes",		archivo: "/salterios/src/evan/ta/3/martes.mp3",		fecha: `${year}-12-16` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Miercoles",	archivo: "/salterios/src/evan/ta/3/miercoles.mp3",	fecha: `${year}-12-17` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Jueves",		archivo: "/salterios/src/evan/ta/3/jueves.mp3",		fecha: `${year}-12-18` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Viernes",		archivo: "/salterios/src/evan/ta/3/viernes.mp3",	fecha: `${year}-12-19` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Sabado",		archivo: "/salterios/src/evan/ta/3/sabado.mp3",		fecha: `${year}-12-20` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Domingo",		archivo: "/salterios/src/evan/ta/4/domingo.mp3",	fecha: `${year}-12-21` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Lunes",		archivo: "/salterios/src/evan/ta/4/lunes.mp3",		fecha: `${year}-12-22` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Martes",		archivo: "/salterios/src/evan/ta/4/martes.mp3",		fecha: `${year}-12-23` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Miercoles",	archivo: "/salterios/src/evan/ta/4/miercoles.mp3",	fecha: `${year}-12-24` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Jueves",		archivo: "/salterios/src/evan/tn/1/jueves.mp3",		fecha: `${year}-12-25` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Viernes",		archivo: "/salterios/src/evan/tn/1/viernes.mp3",	fecha: `${year}-12-26` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Sabado",		archivo: "/salterios/src/evan/tn/1/sabado.mp3",		fecha: `${year}-12-27` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Domingo",		archivo: "/salterios/src/evan/tn/2/domingo.mp3",	fecha: `${year}-12-28` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Lunes",			archivo: "/salterios/src/evan/tn/2/lunes.mp3",		fecha: `${year}-12-29` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Martes",		archivo: "/salterios/src/evan/tn/2/martes.mp3",		fecha: `${year}-12-30` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Miercoles",		archivo: "/salterios/src/evan/tn/2/miercoles.mp3",	fecha: `${year}-12-31` },


];

function obtenerFechaHoy() {
    const hoy = new Date();
    const año = hoy.getFullYear();
    const mes = String(hoy.getMonth() + 1).padStart(2, '0');
    const dia = String(hoy.getDate()).padStart(2, '0');
    return `${año}-${mes}-${dia}`;
}

function cargarAudioPorDefecto() {
    const		fechaHoy = obtenerFechaHoy();
    console.log("Fecha de hoy:",		fechaHoy);

    const audioHoy = audios.find(audio => audio.fecha ===		fechaHoy);
    console.log("Audio encontrado:", audioHoy);

    const reproductor = document.getElementById('audio-player');
    const fuenteAudio = document.getElementById('audio-source');
    const tituloAudio = document.getElementById('titulo-audio');

    if (audioHoy) {
        console.log("Cargando audio:", audioHoy.archivo);
        tituloAudio.textContent = audioHoy.nombre;
        fuenteAudio.src = audioHoy.archivo;
        reproductor.load();
    } else {
        console.log("No hay audio para hoy");
        tituloAudio.textContent = "No hay audio para hoy";
        fuenteAudio.src = "";
        reproductor.load();
    }
}

window.onload = cargarAudioPorDefecto;
