const year = new Date().getFullYear(); // Obtiene el año actual
// const year = 2025; // Si prefieres un año fijo


// Lista de audios con su información
const audios = [

    // DIA DE LOS SANTOS
    { nombre: "Santa María, Madre de Dios", 																archivo: "/ev/tn/01-enero.mp3",		   	fecha: `${year}-01-01` }, // 1ro de Enero, Santa Maria Madre de Dios     
    { nombre: "2 de Enero", 																				archivo: "/ev/tn/02-enero.mp3",	       	fecha: `${year}-01-02` }, // 2 de Enero Santisimo Nombre de nuestro Señor Jesucristo
    { nombre: "3 de Enero", 																				archivo: "/ev/tn/03-enero.mp3",			fecha: `${year}-01-03` }, // 3 de Enero Santisimo Nombre de nuestro Señor Jesucristo
    { nombre: "La Epifanía del Señor", 																		archivo: "/ev/tn/06-enero.mp3",			fecha: `${year}-01-06` }, // 6 de Enero, Epifanía del Señor
    
    
    /*	
    { nombre: "Día de la Altagracia", 																		archivo: "/ev/dias/21enero.mp3",		fecha: `${year}-01-21` }, // 21 de Enero, Día de la Altagracia
    { nombre: "La Conversión de San Pablo, apóstol",														archivo: "/ev/dias/26enero.mp3",		fecha: `${year}-01-25` }, // 25 La Conversión de San Pablo, apóstol
	*/

/* ENERO        */ { nombre: "Navidad, Semana I,Santa María, Madre de Dios, JUEVES",    					archivo: "/ev/tn/01-enero.mp3",			fecha: `${year}-01-01` },
/* ENERO        * / { nombre: "Navidad, Semana I, VIERNES",                              					archivo: "/ev/tn/02-enero.mp3",			fecha: `${year}-01-02` },
/* ENERO        */ { nombre: "Navidad, Semana I, SÁBADO",                               					archivo: "/ev/tn/03-enero.mp3",			fecha: `${year}-01-03` },
/* ENERO        */ { nombre: "Navidad, Semana II, DOMINGO",                              					archivo: "/ev/tn/s02/domingo.mp3",		fecha: `${year}-01-04` },
/* ENERO        */ { nombre: "Navidad, Semana II, LUNES",                                					archivo: "/ev/tn/05-enero.mp3",			fecha: `${year}-01-05` },
/* ENERO        */ { nombre: "Navidad, Semana II,La Epifanía del Señor, MARTES",         					archivo: "/ev/tn/06-enero.mp3",			fecha: `${year}-01-06` },
/* ENERO        */ { nombre: "Navidad, Semana II, MIÉRCOLES",                            					archivo: "/ev/tn/07-enero.mp3",			fecha: `${year}-01-07` },
/* ENERO        */ { nombre: "Navidad, Semana II, JUEVES",                               					archivo: "/ev/tn/08-enero.mp3",			fecha: `${year}-01-08` },
/* ENERO        */ { nombre: "Navidad, Semana II, VIERNES",													archivo: "/ev/tn/09-enero.mp3",			fecha: `${year}-01-09` },
/* ENERO        */ { nombre: "Navidad, Semana II, SÁBADO",                               					archivo: "/ev/tn/10-enero.mp3",			fecha: `${year}-01-10` },
/* ENERO        */ { nombre: "Ordinario, Semana I,El Bautismo del Señor, DOMINGO", 							archivo: "/ev/to/1/domingo.mp3",		fecha: `${year}-01-11` },
/* ENERO        */ { nombre: "Ordinario, Semana I, LUNES", 													archivo: "/ev/to/1/lunes.mp3",			fecha: `${year}-01-12` },
/* ENERO        */ { nombre: "Ordinario, Semana I, MARTES", 												archivo: "/ev/to/1/martes.mp3",			fecha: `${year}-01-13` },
/* ENERO        */ { nombre: "Ordinario, Semana I, MIÉRCOLES", 												archivo: "/ev/to/1/miércoles.mp3",		fecha: `${year}-01-14` },
/* ENERO        */ { nombre: "Ordinario, Semana I, JUEVES", 												archivo: "/ev/to/1/jueves.mp3",			fecha: `${year}-01-15` },
/* ENERO        */ { nombre: "Ordinario, Semana I, VIERNES", 												archivo: "/ev/to/1/viernes.mp3",		fecha: `${year}-01-16` },
/* ENERO        */ { nombre: "Ordinario, Semana I, SÁBADO", 												archivo: "/ev/to/1/sábado.mp3",			fecha: `${year}-01-17` },
/* ENERO        */ { nombre: "Ordinario, Semana II, DOMINGO", 												archivo: "/ev/to/2/domingo.mp3",		fecha: `${year}-01-18` },
/* ENERO        */ { nombre: "Ordinario, Semana II, LUNES", 												archivo: "/ev/to/2/lunes.mp3",			fecha: `${year}-01-19` },
/* ENERO        */ { nombre: "Ordinario, Semana II, MARTES", 												archivo: "/ev/to/2/martes.mp3",			fecha: `${year}-01-20` },

/* ENERO        */ { nombre: "Ordinario, Semana II, MIÉRCOLES", 											archivo: "/ev/to/2/miércoles.mp3",		fecha: `${year}-01-21` },

/* ENERO        */ { nombre: "Ordinario, Semana II, JUEVES", 												archivo: "/ev/to/2/jueves.mp3",			fecha: `${year}-01-22` },
/* ENERO        */ { nombre: "Ordinario, Semana II, VIERNES", 												archivo: "/ev/to/2/viernes.mp3",		fecha: `${year}-01-23` },
/* ENERO        */ { nombre: "Ordinario, Semana II, SÁBADO",												archivo: "/ev/to/2/sábado.mp3",			fecha: `${year}-01-24` },
/* ENERO        */ { nombre: "Ordinario, Semana III, DOMINGO",												archivo: "/ev/to/3/domingo.mp3",		fecha: `${year}-01-25` },
/* ENERO        */ { nombre: "Ordinario, Semana III, LUNES", 												archivo: "/ev/to/3/lunes.mp3",			fecha: `${year}-01-26` },
/* ENERO        */ { nombre: "Ordinario, Semana III, MARTES", 												archivo: "/ev/to/3/martes.mp3",			fecha: `${year}-01-27` },
/* ENERO        */ { nombre: "Ordinario, Semana III, MIÉRCOLES", 											archivo: "/ev/to/3/miércoles.mp3",		fecha: `${year}-01-28` },
/* ENERO        */ { nombre: "Ordinario, Semana III, JUEVES", 												archivo: "/ev/to/3/jueves.mp3",			fecha: `${year}-01-29` },
/* ENERO        */ { nombre: "Ordinario, Semana III, VIERNES", 												archivo: "/ev/to/3/viernes.mp3",		fecha: `${year}-01-30` },
/* ENERO        */ { nombre: "Ordinario, Semana III, SÁBADO",												archivo: "/ev/to/3/sábado.mp3",			fecha: `${year}-01-31` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, DOMINGO", 											archivo: "/ev/to/4/domingo.mp3",		fecha: `${year}-02-01` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, LUNES",												archivo: "/ev/to/4/lunes.mp3",			fecha: `${year}-02-02` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, MARTES", 												archivo: "/ev/to/4/martes.mp3",			fecha: `${year}-02-03` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, MIÉRCOLES",											archivo: "/ev/to/4/miércoles.mp3",		fecha: `${year}-02-04` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, JUEVES", 												archivo: "/ev/to/4/jueves.mp3",			fecha: `${year}-02-05` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, VIERNES", 											archivo: "/ev/to/4/viernes.mp3",		fecha: `${year}-02-06` },
/* FEBRERO        */ { nombre: "Ordinario, Semana IV, SÁBADO",												archivo: "/ev/to/4/sábado.mp3",			fecha: `${year}-02-07` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, DOMINGO",												archivo: "/ev/to/5/domingo.mp3",		fecha: `${year}-02-08` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, LUNES", 												archivo: "/ev/to/5/lunes.mp3",			fecha: `${year}-02-09` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, MARTES", 												archivo: "/ev/to/5/martes.mp3",			fecha: `${year}-02-10` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, MIÉRCOLES", 											archivo: "/ev/to/5/miércoles.mp3",		fecha: `${year}-02-11` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, JUEVES", 												archivo: "/ev/to/5/jueves.mp3",			fecha: `${year}-02-12` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, VIERNES", 												archivo: "/ev/to/5/viernes.mp3",		fecha: `${year}-02-13` },
/* FEBRERO        */ { nombre: "Ordinario, Semana V, SÁBADO", 												archivo: "/ev/to/5/sábado.mp3",			fecha: `${year}-02-14` },
/* FEBRERO        */ { nombre: "Ordinario, Semana VI, DOMINGO", 											archivo: "/ev/to/6/domingo.mp3",		fecha: `${year}-02-15` },
/* FEBRERO        */ { nombre: "Ordinario, Semana VI, LUNES",												archivo: "/ev/to/6/lunes.mp3",			fecha: `${year}-02-16` },
/* FEBRERO        */ { nombre: "Ordinario, Semana VI, MARTES", 												archivo: "/ev/to/6/martes.mp3",			fecha: `${year}-02-17` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I,Miércoles de Ceniza, MIÉRCOLES", 						archivo: "/ev/tc/1/miércoles.mp3",		fecha: `${year}-02-18` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, Jueves después del Miércoles de Ceniza, JUEVES", 		archivo: "/ev/tc/1/jueves.mp3",			fecha: `${year}-02-19` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, Viernes después del Miércoles de Ceniza, VIERNES", 		archivo: "/ev/tc/1/viernes.mp3",		fecha: `${year}-02-20` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, Sábado después del Miércoles de Ceniza, SÁBADO", 		archivo: "/ev/tc/1/sábado.mp3",			fecha: `${year}-02-21` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, DOMINGO", 												archivo: "/ev/tc/1/domingo.mp3",		fecha: `${year}-02-22` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, LUNES", 												archivo: "/ev/tc/1/lunes.mp3",			fecha: `${year}-02-23` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, MARTES", 												archivo: "/ev/tc/1/martes.mp3",			fecha: `${year}-02-24` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, MIÉRCOLES", 											archivo: "/ev/tc/1/miércoles.mp3",		fecha: `${year}-02-25` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, JUEVES", 												archivo: "/ev/tc/1/jueves.mp3",			fecha: `${year}-02-26` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, VIERNES", 												archivo: "/ev/tc/1/viernes.mp3",		fecha: `${year}-02-27` },
/* FEBRERO        */ { nombre: "Cuaresma, Semana I, SÁBADO", 												archivo: "/ev/tc/1/sábado.mp3",			fecha: `${year}-02-28` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, DOMINGO", 												archivo: "/ev/tc/2/domingo.mp3",		fecha: `${year}-03-01` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, LUNES", 													archivo: "/ev/tc/2/lunes.mp3",			fecha: `${year}-03-02` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, MARTES", 												archivo: "/ev/tc/2/martes.mp3",			fecha: `${year}-03-03` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, MIÉRCOLES", 												archivo: "/ev/tc/2/miércoles.mp3",		fecha: `${year}-03-04` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, JUEVES", 												archivo: "/ev/tc/2/jueves.mp3",			fecha: `${year}-03-05` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, VIERNES", 												archivo: "/ev/tc/2/viernes.mp3",		fecha: `${year}-03-06` },
/* MARZO        */ { nombre: "Cuaresma, Semana II, SÁBADO", 												archivo: "/ev/tc/2/sábado.mp3",			fecha: `${year}-03-07` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, DOMINGO",												archivo: "/ev/tc/3/domingo.mp3",		fecha: `${year}-03-08` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, LUNES",													archivo: "/ev/tc/3/lunes.mp3",			fecha: `${year}-03-09` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, MARTES", 												archivo: "/ev/tc/3/martes.mp3",			fecha: `${year}-03-10` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, MIÉRCOLES", 											archivo: "/ev/tc/3/miércoles.mp3",		fecha: `${year}-03-11` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, JUEVES", 												archivo: "/ev/tc/3/jueves.mp3",			fecha: `${year}-03-12` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, VIERNES", 												archivo: "/ev/tc/3/viernes.mp3",		fecha: `${year}-03-13` },
/* MARZO        */ { nombre: "Cuaresma, Semana III, SÁBADO", 												archivo: "/ev/tc/3/sábado.mp3",			fecha: `${year}-03-14` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, Domingo «Laetare», DOMINGO", 							archivo: "/ev/tc/4/domingo.mp3",		fecha: `${year}-03-15` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, LUNES", 													archivo: "/ev/tc/4/lunes.mp3",			fecha: `${year}-03-16` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, MARTES", 												archivo: "/ev/tc/4/martes.mp3",			fecha: `${year}-03-17` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, MIÉRCOLES", 												archivo: "/ev/tc/4/miércoles.mp3",		fecha: `${year}-03-18` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, JUEVES", 												archivo: "/ev/tc/4/jueves.mp3",			fecha: `${year}-03-19` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, VIERNES", 												archivo: "/ev/tc/4/viernes.mp3",		fecha: `${year}-03-20` },
/* MARZO        */ { nombre: "Cuaresma, Semana IV, SÁBADO", 												archivo: "/ev/tc/4/sábado.mp3",			fecha: `${year}-03-21` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, DOMINGO", 												archivo: "/ev/tc/5/domingo.mp3",		fecha: `${year}-03-22` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, LUNES", 													archivo: "/ev/tc/5/lunes.mp3",			fecha: `${year}-03-23` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, MARTES", 													archivo: "/ev/tc/5/martes.mp3",			fecha: `${year}-03-24` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, La Anunciación del Señor, MIÉRCOLES", 					archivo: "/ev/tc/5/miércoles.mp3",		fecha: `${year}-03-25` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, JUEVES", 													archivo: "/ev/tc/5/jueves.mp3",			fecha: `${year}-03-26` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, VIERNES", 												archivo: "/ev/tc/5/viernes.mp3",		fecha: `${year}-03-27` },
/* MARZO        */ { nombre: "Cuaresma, Semana V, SÁBADO",													archivo: "/ev/tc/5/sábado.mp3",			fecha: `${year}-03-28` },
/* MARZO        */ { nombre: "Cuaresma, Semana VI, Domingo de Ramos en la Pasión del Señor, DOMINGO", 		archivo: "/ev/tc/6/domingo.mp3",		fecha: `${year}-03-29` },
/* MARZO        */ { nombre: "Cuaresma, Semana VI, Lunes Santo, LUNES", 									archivo: "/ev/tc/6/lunes.mp3",			fecha: `${year}-03-30` },
/* MARZO        */ { nombre: "Cuaresma, Semana VI, Martes Santo, MARTES", 									archivo: "/ev/tc/6/martes.mp3",			fecha: `${year}-03-31` },
/* ABRIL        */ { nombre: "Cuaresma, Semana VI, Miercoles Santo, MIÉRCOLES",								archivo: "/ev/tc/6/miércoles.mp3",		fecha: `${year}-04-01` },
/* ABRIL        */ { nombre: "Cuaresma, Semana VI, Jueves Santo en la Cena del Señor, JUEVES", 				archivo: "/ev/tc/6/jueves.mp3",			fecha: `${year}-04-02` },
/* ABRIL        */ { nombre: "Cuaresma, Semana VI, Viernes Santo en la Pasión del Señor, VIERNES",			archivo: "/ev/tc/6/viernes.mp3",		fecha: `${year}-04-03` },
/* ABRIL        */ { nombre: "Cuaresma, Semana VI, Sábado Santo de la Sepultura del Señor, SÁBADO", 		archivo: "/ev/tc/6/sábado.mp3",			fecha: `${year}-04-04` },
/* ABRIL        */ { nombre: "Pascual, Semana I, Domingo de Pascua de la Resurrección del Señor, DOMINGO",	archivo: "/ev/tp/1/domingo.mp3",		fecha: `${year}-04-05` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, LUNES", 									archivo: "/ev/tp/1/lunes.mp3",			fecha: `${year}-04-06` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, MARTES", 									archivo: "/ev/tp/1/martes.mp3",			fecha: `${year}-04-07` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, MIÉRCOLES", 								archivo: "/ev/tp/1/miércoles.mp3",		fecha: `${year}-04-08` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, JUEVES", 									archivo: "/ev/tp/1/jueves.mp3",			fecha: `${year}-04-09` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, VIERNES", 								archivo: "/ev/tp/1/viernes.mp3",		fecha: `${year}-04-10` },
/* ABRIL        */ { nombre: "Pascual, Semana I,Octava de Pascua, SÁBADO", 									archivo: "/ev/tp/1/sábado.mp3",			fecha: `${year}-04-11` },
/* ABRIL        */ { nombre: "Pascual, Semana II,Divina Misericordia, DOMINGO", 							archivo: "/ev/tp/2/domingo.mp3",		fecha: `${year}-04-12` },
/* ABRIL        */ { nombre: "Pascual, Semana II, LUNES", 													archivo: "/ev/tp/2/lunes.mp3",			fecha: `${year}-04-13` },
/* ABRIL        */ { nombre: "Pascual, Semana II, MARTES", 													archivo: "/ev/tp/2/martes.mp3",			fecha: `${year}-04-14` },
/* ABRIL        */ { nombre: "Pascual, Semana II, MIÉRCOLES", 												archivo: "/ev/tp/2/miércoles.mp3",		fecha: `${year}-04-15` },
/* ABRIL        */ { nombre: "Pascual, Semana II, JUEVES", 													archivo: "/ev/tp/2/jueves.mp3",			fecha: `${year}-04-16` },
/* ABRIL        */ { nombre: "Pascual, Semana II, VIERNES", 												archivo: "/ev/tp/2/viernes.mp3",		fecha: `${year}-04-17` },
/* ABRIL        */ { nombre: "Pascual, Semana II, SÁBADO", 													archivo: "/ev/tp/2/sábado.mp3",			fecha: `${year}-04-18` },
/* ABRIL        */ { nombre: "Pascual, Semana III, DOMINGO", 												archivo: "/ev/tp/3/domingo.mp3",		fecha: `${year}-04-19` },
/* ABRIL        */ { nombre: "Pascual, Semana III, LUNES", 													archivo: "/ev/tp/3/lunes.mp3",			fecha: `${year}-04-20` },
/* ABRIL        */ { nombre: "Pascual, Semana III, MARTES", 												archivo: "/ev/tp/3/martes.mp3",			fecha: `${year}-04-21` },
/* ABRIL        */ { nombre: "Pascual, Semana III, MIÉRCOLES", 												archivo: "/ev/tp/3/miércoles.mp3",		fecha: `${year}-04-22` },
/* ABRIL        */ { nombre: "Pascual, Semana III, JUEVES", 												archivo: "/ev/tp/3/jueves.mp3",			fecha: `${year}-04-23` },
/* ABRIL        */ { nombre: "Pascual, Semana III, VIERNES", 												archivo: "/ev/tp/3/viernes.mp3",		fecha: `${year}-04-24` },
/* ABRIL        */ { nombre: "Pascual, Semana III, SÁBADO", 												archivo: "/ev/tp/3/sábado.mp3",			fecha: `${year}-04-25` },
/* ABRIL        */ { nombre: "Pascual, Semana IV, DOMINGO", 												archivo: "/ev/tp/4/domingo.mp3",		fecha: `${year}-04-26` },
/* ABRIL        */ { nombre: "Pascual, Semana IV, LUNES", 													archivo: "/ev/tp/4/lunes.mp3",			fecha: `${year}-04-27` },
/* ABRIL        */ { nombre: "Pascual, Semana IV, MARTES", 													archivo: "/ev/tp/4/martes.mp3",			fecha: `${year}-04-28` },
/* ABRIL        */ { nombre: "Pascual, Semana IV, MIÉRCOLES", 												archivo: "/ev/tp/4/miércoles.mp3",		fecha: `${year}-04-29` },
/* ABRIL        */ { nombre: "Pascual, Semana IV, JUEVES", 													archivo: "/ev/tp/4/jueves.mp3",			fecha: `${year}-04-30` },
/* MAYO        */ { nombre: "Pascual, Semana IV, VIERNES", 													archivo: "/ev/tp/4/viernes.mp3",		fecha: `${year}-05-01` },
/* MAYO        */ { nombre: "Pascual, Semana IV, SÁBADO", 													archivo: "/ev/tp/4/sábado.mp3",			fecha: `${year}-05-02` },
/* MAYO        */ { nombre: "Pascual, Semana V, DOMINGO", 													archivo: "/ev/tp/5/domingo.mp3",		fecha: `${year}-05-03` },
/* MAYO        */ { nombre: "Pascual, Semana V, LUNES", 													archivo: "/ev/tp/5/lunes.mp3",			fecha: `${year}-05-04` },
/* MAYO        */ { nombre: "Pascual, Semana V, MARTES", 													archivo: "/ev/tp/5/martes.mp3",			fecha: `${year}-05-05` },
/* MAYO        */ { nombre: "Pascual, Semana V, MIÉRCOLES", 												archivo: "/ev/tp/5/miércoles.mp3",		fecha: `${year}-05-06` },
/* MAYO        */ { nombre: "Pascual, Semana V, JUEVES", 													archivo: "/ev/tp/5/jueves.mp3",			fecha: `${year}-05-07` },
/* MAYO        */ { nombre: "Pascual, Semana V, VIERNES", 													archivo: "/ev/tp/5/viernes.mp3",		fecha: `${year}-05-08` },
/* MAYO        */ { nombre: "Pascual, Semana V, SÁBADO", 													archivo: "/ev/tp/5/sábado.mp3",			fecha: `${year}-05-09` },
/* MAYO        */ { nombre: "Pascual, Semana VI, DOMINGO", 													archivo: "/ev/tp/6/domingo.mp3",		fecha: `${year}-05-10` },
/* MAYO        */ { nombre: "Pascual, Semana VI, LUNES", 													archivo: "/ev/tp/6/lunes.mp3",			fecha: `${year}-05-11` },
/* MAYO        */ { nombre: "Pascual, Semana VI, MARTES", 													archivo: "/ev/tp/6/martes.mp3",			fecha: `${year}-05-12` },
/* MAYO        */ { nombre: "Pascual, Semana VI, MIÉRCOLES", 												archivo: "/ev/tp/6/miércoles.mp3",		fecha: `${year}-05-13` },
/* MAYO        */ { nombre: "Pascual, Semana VI, JUEVES", 													archivo: "/ev/tp/6/jueves.mp3",			fecha: `${year}-05-14` },
/* MAYO        */ { nombre: "Pascual, Semana VI, VIERNES", 													archivo: "/ev/tp/6/viernes.mp3",		fecha: `${year}-05-15` },
/* MAYO        */ { nombre: "Pascual, Semana VI, SÁBADO", 													archivo: "/ev/tp/6/sábado.mp3",			fecha: `${year}-05-16` },
/* MAYO        */ { nombre: "Pascual, Semana VII, La Ascensión del Señor, DOMINGO", 						archivo: "/ev/tp/7/domingo.mp3",		fecha: `${year}-05-17` },
/* MAYO        */ { nombre: "Pascual, Semana VII, LUNES", 													archivo: "/ev/tp/7/lunes.mp3",			fecha: `${year}-05-18` },
/* MAYO        */ { nombre: "Pascual, Semana VII, MARTES", 													archivo: "/ev/tp/7/martes.mp3",			fecha: `${year}-05-19` },
/* MAYO        */ { nombre: "Pascual, Semana VII, MIÉRCOLES", 												archivo: "/ev/tp/7/miércoles.mp3",		fecha: `${year}-05-20` },
/* MAYO        */ { nombre: "Pascual, Semana VII, JUEVES", 													archivo: "/ev/tp/7/jueves.mp3",			fecha: `${year}-05-21` },
/* MAYO        */ { nombre: "Pascual, Semana VII, VIERNES", 												archivo: "/ev/tp/7/viernes.mp3",		fecha: `${year}-05-22` },
/* MAYO        */ { nombre: "Pascual, Semana VII, SÁBADO", 													archivo: "/ev/tp/7/sábado.mp3",			fecha: `${year}-05-23` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII,Domingo de Pentecostés, DOMINGO", 						archivo: "/ev/to/8/domingo.mp3",		fecha: `${year}-05-24` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, LUNES", 												archivo: "/ev/to/8/lunes.mp3",			fecha: `${year}-05-25` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, MARTES", 												archivo: "/ev/to/8/martes.mp3",			fecha: `${year}-05-26` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, MIÉRCOLES", 											archivo: "/ev/to/8/miércoles.mp3",		fecha: `${year}-05-27` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, JUEVES", 												archivo: "/ev/to/8/jueves.mp3",			fecha: `${year}-05-28` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, VIERNES", 												archivo: "/ev/to/8/viernes.mp3",		fecha: `${year}-05-29` },
/* MAYO        */ { nombre: "Ordinario, Semana VIII, SÁBADO", 												archivo: "/ev/to/8/sábado.mp3",			fecha: `${year}-05-30` },
/* MAYO        */ { nombre: "Ordinario, Semana IX, La Santísima Trinidad, DOMINGO", 						archivo: "/ev/to/9/domingo.mp3",		fecha: `${year}-05-31` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, LUNES", 												archivo: "/ev/to/9/lunes.mp3",			fecha: `${year}-06-01` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, MARTES", 												archivo: "/ev/to/9/martes.mp3",			fecha: `${year}-06-02` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, MIÉRCOLES", 											archivo: "/ev/to/9/miércoles.mp3",		fecha: `${year}-06-03` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, JUEVES", 												archivo: "/ev/to/9/jueves.mp3",			fecha: `${year}-06-04` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, VIERNES", 												archivo: "/ev/to/9/viernes.mp3",		fecha: `${year}-06-05` },
/* JUNIO        */ { nombre: "Ordinario, Semana IX, SÁBADO", 												archivo: "/ev/to/9/sábado.mp3",			fecha: `${year}-06-06` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, El Cuerpo y la Sangre Santísimos de Cristo, DOMINGO", 	archivo: "/ev/to/10/domingo.mp3",		fecha: `${year}-06-07` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, LUNES", 													archivo: "/ev/to/10/lunes.mp3",			fecha: `${year}-06-08` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, MARTES", 												archivo: "/ev/to/10/martes.mp3",		fecha: `${year}-06-09` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, MIÉRCOLES", 												archivo: "/ev/to/10/miércoles.mp3",		fecha: `${year}-06-10` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, JUEVES", 												archivo: "/ev/to/10/jueves.mp3",		fecha: `${year}-06-11` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, El Sagrado Corazón de Jesús, VIERNES", 					archivo: "/ev/to/10/viernes.mp3",		fecha: `${year}-06-12` },
/* JUNIO        */ { nombre: "Ordinario, Semana X, SÁBADO", 												archivo: "/ev/to/10/sábado.mp3",		fecha: `${year}-06-13` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, DOMINGO", 												archivo: "/ev/to/11/domingo.mp3",		fecha: `${year}-06-14` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, LUNES", 												archivo: "/ev/to/11/lunes.mp3",			fecha: `${year}-06-15` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, MARTES", 												archivo: "/ev/to/11/martes.mp3",		fecha: `${year}-06-16` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, MIÉRCOLES", 											archivo: "/ev/to/11/miércoles.mp3",		fecha: `${year}-06-17` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, JUEVES", 												archivo: "/ev/to/11/jueves.mp3",		fecha: `${year}-06-18` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, VIERNES", 												archivo: "/ev/to/11/viernes.mp3",		fecha: `${year}-06-19` },
/* JUNIO        */ { nombre: "Ordinario, Semana XI, SÁBADO", 												archivo: "/ev/to/11/sábado.mp3",		fecha: `${year}-06-20` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, DOMINGO", 												archivo: "/ev/to/12/domingo.mp3",		fecha: `${year}-06-21` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, LUNES", 												archivo: "/ev/to/12/lunes.mp3",			fecha: `${year}-06-22` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, MARTES", 												archivo: "/ev/to/12/martes.mp3",		fecha: `${year}-06-23` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, El Nacimiento de San Juan Bautista, MIÉRCOLES", 		archivo: "/ev/to/12/miércoles.mp3",		fecha: `${year}-06-24` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, JUEVES", 												archivo: "/ev/to/12/jueves.mp3",		fecha: `${year}-06-25` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, VIERNES", 												archivo: "/ev/to/12/viernes.mp3",		fecha: `${year}-06-26` },
/* JUNIO        */ { nombre: "Ordinario, Semana XII, SÁBADO", 												archivo: "/ev/to/12/sábado.mp3",		fecha: `${year}-06-27` },
/* JUNIO        */ { nombre: "Ordinario, Semana XIII, DOMINGO", 											archivo: "/ev/to/13/domingo.mp3",		fecha: `${year}-06-28` },
/* JUNIO        */ { nombre: "Ordinario, Semana XIII, Santos Pedro y Pablo, apóstoles, LUNES", 				archivo: "/ev/to/13/lunes.mp3",			fecha: `${year}-06-29` },
/* JUNIO        */ { nombre: "Ordinario, Semana XIII, MARTES", 												archivo: "/ev/to/13/martes.mp3",		fecha: `${year}-06-30` },
/* JULIO        */ { nombre: "Ordinario, Semana XIII, MIÉRCOLES", 											archivo: "/ev/to/13/miércoles.mp3",		fecha: `${year}-07-01` },
/* JULIO        */ { nombre: "Ordinario, Semana XIII, JUEVES", 												archivo: "/ev/to/13/jueves.mp3",		fecha: `${year}-07-02` },
/* JULIO        */ { nombre: "Ordinario, Semana XIII, VIERNES", 											archivo: "/ev/to/13/viernes.mp3",		fecha: `${year}-07-03` },
/* JULIO        */ { nombre: "Ordinario, Semana XIII, SÁBADO", 												archivo: "/ev/to/13/sábado.mp3",		fecha: `${year}-07-04` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, DOMINGO", 												archivo: "/ev/to/14/domingo.mp3",		fecha: `${year}-07-05` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, LUNES", 												archivo: "/ev/to/14/lunes.mp3",			fecha: `${year}-07-06` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, MARTES", 												archivo: "/ev/to/14/martes.mp3",		fecha: `${year}-07-07` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, MIÉRCOLES", 											archivo: "/ev/to/14/miércoles.mp3",		fecha: `${year}-07-08` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, JUEVES", 												archivo: "/ev/to/14/jueves.mp3",		fecha: `${year}-07-09` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, VIERNES", 												archivo: "/ev/to/14/viernes.mp3",		fecha: `${year}-07-10` },
/* JULIO        */ { nombre: "Ordinario, Semana XIV, SÁBADO", 												archivo: "/ev/to/14/sábado.mp3",		fecha: `${year}-07-11` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, DOMINGO", 												archivo: "/ev/to/15/domingo.mp3",		fecha: `${year}-07-12` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, LUNES", 												archivo: "/ev/to/15/lunes.mp3",			fecha: `${year}-07-13` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, MARTES", 												archivo: "/ev/to/15/martes.mp3",		fecha: `${year}-07-14` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, MIÉRCOLES", 											archivo: "/ev/to/15/miércoles.mp3",		fecha: `${year}-07-15` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, JUEVES", 												archivo: "/ev/to/15/jueves.mp3",		fecha: `${year}-07-16` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, VIERNES", 												archivo: "/ev/to/15/viernes.mp3",		fecha: `${year}-07-17` },
/* JULIO        */ { nombre: "Ordinario, Semana XV, SÁBADO", 												archivo: "/ev/to/15/sábado.mp3",		fecha: `${year}-07-18` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, DOMINGO", 												archivo: "/ev/to/16/domingo.mp3",		fecha: `${year}-07-19` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, LUNES", 												archivo: "/ev/to/16/lunes.mp3",			fecha: `${year}-07-20` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, MARTES", 												archivo: "/ev/to/16/martes.mp3",		fecha: `${year}-07-21` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, MIÉRCOLES", 											archivo: "/ev/to/16/miércoles.mp3",		fecha: `${year}-07-22` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, JUEVES", 												archivo: "/ev/to/16/jueves.mp3",		fecha: `${year}-07-23` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, VIERNES", 												archivo: "/ev/to/16/viernes.mp3",		fecha: `${year}-07-24` },
/* JULIO        */ { nombre: "Ordinario, Semana XVI, SÁBADO", 												archivo: "/ev/to/16/sábado.mp3",		fecha: `${year}-07-25` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, DOMINGO", 											archivo: "/ev/to/17/domingo.mp3",		fecha: `${year}-07-26` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, LUNES", 												archivo: "/ev/to/17/lunes.mp3",			fecha: `${year}-07-27` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, MARTES", 												archivo: "/ev/to/17/martes.mp3",		fecha: `${year}-07-28` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, MIÉRCOLES", 											archivo: "/ev/to/17/miércoles.mp3",		fecha: `${year}-07-29` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, JUEVES", 												archivo: "/ev/to/17/jueves.mp3",		fecha: `${year}-07-30` },
/* JULIO        */ { nombre: "Ordinario, Semana XVII, VIERNES", 											archivo: "/ev/to/17/viernes.mp3",		fecha: `${year}-07-31` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVII, SÁBADO", 											archivo: "/ev/to/17/sábado.mp3",		fecha: `${year}-08-01` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, DOMINGO", 											archivo: "/ev/to/18/domingo.mp3",		fecha: `${year}-08-02` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, LUNES", 											archivo: "/ev/to/18/lunes.mp3",			fecha: `${year}-08-03` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, MARTES", 											archivo: "/ev/to/18/martes.mp3",		fecha: `${year}-08-04` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, MIÉRCOLES", 										archivo: "/ev/to/18/miércoles.mp3",		fecha: `${year}-08-05` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, JUEVES", 											archivo: "/ev/to/18/jueves.mp3",		fecha: `${year}-08-06` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, VIERNES", 											archivo: "/ev/to/18/viernes.mp3",		fecha: `${year}-08-07` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XVIII, SÁBADO", 											archivo: "/ev/to/18/sábado.mp3",		fecha: `${year}-08-08` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, DOMINGO", 											archivo: "/ev/to/19/domingo.mp3",		fecha: `${year}-08-09` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, LUNES", 												archivo: "/ev/to/19/lunes.mp3",			fecha: `${year}-08-10` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, MARTES", 												archivo: "/ev/to/19/martes.mp3",		fecha: `${year}-08-11` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, MIÉRCOLES", 											archivo: "/ev/to/19/miércoles.mp3",		fecha: `${year}-08-12` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, JUEVES", 												archivo: "/ev/to/19/jueves.mp3",		fecha: `${year}-08-13` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, VIERNES", 											archivo: "/ev/to/19/viernes.mp3",		fecha: `${year}-08-14` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XIX, SÁBADO", 												archivo: "/ev/to/19/sábado.mp3",		fecha: `${year}-08-15` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, DOMINGO", 												archivo: "/ev/to/20/domingo.mp3",		fecha: `${year}-08-16` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, LUNES", 												archivo: "/ev/to/20/lunes.mp3",			fecha: `${year}-08-17` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, MARTES", 												archivo: "/ev/to/20/martes.mp3",		fecha: `${year}-08-18` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, MIÉRCOLES", 											archivo: "/ev/to/20/miércoles.mp3",		fecha: `${year}-08-19` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, JUEVES", 												archivo: "/ev/to/20/jueves.mp3",		fecha: `${year}-08-20` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, VIERNES", 												archivo: "/ev/to/20/viernes.mp3",		fecha: `${year}-08-21` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XX, SÁBADO", 												archivo: "/ev/to/20/sábado.mp3",		fecha: `${year}-08-22` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, DOMINGO", 											archivo: "/ev/to/21/domingo.mp3",		fecha: `${year}-08-23` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, LUNES", 												archivo: "/ev/to/21/lunes.mp3",			fecha: `${year}-08-24` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, MARTES", 												archivo: "/ev/to/21/martes.mp3",		fecha: `${year}-08-25` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, MIÉRCOLES", 											archivo: "/ev/to/21/miércoles.mp3",		fecha: `${year}-08-26` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, JUEVES", 												archivo: "/ev/to/21/jueves.mp3",		fecha: `${year}-08-27` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, VIERNES", 											archivo: "/ev/to/21/viernes.mp3",		fecha: `${year}-08-28` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXI, SÁBADO", 												archivo: "/ev/to/21/sábado.mp3",		fecha: `${year}-08-29` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXII, DOMINGO", 											archivo: "/ev/to/22/domingo.mp3",		fecha: `${year}-08-30` },
/* AGOSTO        */ { nombre: "Ordinario, Semana XXII, LUNES", 												archivo: "/ev/to/22/lunes.mp3",			fecha: `${year}-08-31` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXII, MARTES", 										archivo: "/ev/to/22/martes.mp3",		fecha: `${year}-09-01` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXII, MIÉRCOLES", 										archivo: "/ev/to/22/miércoles.mp3",		fecha: `${year}-09-02` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXII, JUEVES", 										archivo: "/ev/to/22/jueves.mp3",		fecha: `${year}-09-03` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXII, VIERNES", 										archivo: "/ev/to/22/viernes.mp3",		fecha: `${year}-09-04` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXII, SÁBADO", 										archivo: "/ev/to/22/sábado.mp3",		fecha: `${year}-09-05` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, DOMINGO", 										archivo: "/ev/to/23/domingo.mp3",		fecha: `${year}-09-06` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, LUNES", 										archivo: "/ev/to/23/lunes.mp3",			fecha: `${year}-09-07` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, MARTES", 										archivo: "/ev/to/23/martes.mp3",		fecha: `${year}-09-08` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, MIÉRCOLES", 									archivo: "/ev/to/23/miércoles.mp3",		fecha: `${year}-09-09` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, JUEVES", 										archivo: "/ev/to/23/jueves.mp3",		fecha: `${year}-09-10` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, VIERNES", 										archivo: "/ev/to/23/viernes.mp3",		fecha: `${year}-09-11` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIII, SÁBADO", 										archivo: "/ev/to/23/sábado.mp3",		fecha: `${year}-09-12` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, DOMINGO", 										archivo: "/ev/to/24/domingo.mp3",		fecha: `${year}-09-13` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, LUNES", 											archivo: "/ev/to/24/lunes.mp3",			fecha: `${year}-09-14` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, MARTES", 										archivo: "/ev/to/24/martes.mp3",		fecha: `${year}-09-15` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, MIÉRCOLES", 										archivo: "/ev/to/24/miércoles.mp3",		fecha: `${year}-09-16` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, JUEVES", 										archivo: "/ev/to/24/jueves.mp3",		fecha: `${year}-09-17` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, VIERNES", 										archivo: "/ev/to/24/viernes.mp3",		fecha: `${year}-09-18` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXIV, SÁBADO", 										archivo: "/ev/to/24/sábado.mp3",		fecha: `${year}-09-19` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, DOMINGO", 										archivo: "/ev/to/25/domingo.mp3",		fecha: `${year}-09-20` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, LUNES", 											archivo: "/ev/to/25/lunes.mp3",			fecha: `${year}-09-21` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, MARTES", 											archivo: "/ev/to/25/martes.mp3",		fecha: `${year}-09-22` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, MIÉRCOLES", 										archivo: "/ev/to/25/miércoles.mp3",		fecha: `${year}-09-23` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, JUEVES", 											archivo: "/ev/to/25/jueves.mp3",		fecha: `${year}-09-24` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, VIERNES", 										archivo: "/ev/to/25/viernes.mp3",		fecha: `${year}-09-25` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXV, SÁBADO", 											archivo: "/ev/to/25/sábado.mp3",		fecha: `${year}-09-26` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXVI, DOMINGO", 										archivo: "/ev/to/26/domingo.mp3",		fecha: `${year}-09-27` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXVI, LUNES", 											archivo: "/ev/to/26/lunes.mp3",			fecha: `${year}-09-28` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXVI, MARTES", 										archivo: "/ev/to/26/martes.mp3",		fecha: `${year}-09-29` },
/* SEPTIEMBRE        */ { nombre: "Ordinario, Semana XXVI, MIÉRCOLES", 										archivo: "/ev/to/26/miércoles.mp3",		fecha: `${year}-09-30` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVI, JUEVES", 											archivo: "/ev/to/26/jueves.mp3",		fecha: `${year}-10-01` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVI, VIERNES", 											archivo: "/ev/to/26/viernes.mp3",		fecha: `${year}-10-02` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVI, SÁBADO", 											archivo: "/ev/to/26/sábado.mp3",		fecha: `${year}-10-03` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, DOMINGO", 											archivo: "/ev/to/27/domingo.mp3",		fecha: `${year}-10-04` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, LUNES", 											archivo: "/ev/to/27/lunes.mp3",			fecha: `${year}-10-05` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, MARTES", 											archivo: "/ev/to/27/martes.mp3",		fecha: `${year}-10-06` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, MIÉRCOLES", 										archivo: "/ev/to/27/miércoles.mp3",		fecha: `${year}-10-07` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, JUEVES", 											archivo: "/ev/to/27/jueves.mp3",		fecha: `${year}-10-08` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, VIERNES", 											archivo: "/ev/to/27/viernes.mp3",		fecha: `${year}-10-09` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVII, SÁBADO", 											archivo: "/ev/to/27/sábado.mp3",		fecha: `${year}-10-10` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, DOMINGO", 										archivo: "/ev/to/28/domingo.mp3",		fecha: `${year}-10-11` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, LUNES", 											archivo: "/ev/to/28/lunes.mp3",			fecha: `${year}-10-12` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, MARTES", 											archivo: "/ev/to/28/martes.mp3",		fecha: `${year}-10-13` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, MIÉRCOLES", 										archivo: "/ev/to/28/miércoles.mp3",		fecha: `${year}-10-14` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, JUEVES", 											archivo: "/ev/to/28/jueves.mp3",		fecha: `${year}-10-15` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, VIERNES", 										archivo: "/ev/to/28/viernes.mp3",		fecha: `${year}-10-16` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXVIII, SÁBADO", 											archivo: "/ev/to/28/sábado.mp3",		fecha: `${year}-10-17` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, DOMINGO", 											archivo: "/ev/to/29/domingo.mp3",		fecha: `${year}-10-18` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, LUNES", 											archivo: "/ev/to/29/lunes.mp3",			fecha: `${year}-10-19` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, MARTES", 											archivo: "/ev/to/29/martes.mp3",		fecha: `${year}-10-20` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, MIÉRCOLES", 										archivo: "/ev/to/29/miércoles.mp3",		fecha: `${year}-10-21` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, JUEVES", 											archivo: "/ev/to/29/jueves.mp3",		fecha: `${year}-10-22` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, VIERNES", 											archivo: "/ev/to/29/viernes.mp3",		fecha: `${year}-10-23` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXIX, SÁBADO", 											archivo: "/ev/to/29/sábado.mp3",		fecha: `${year}-10-24` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, DOMINGO", 											archivo: "/ev/to/30/domingo.mp3",		fecha: `${year}-10-25` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, LUNES", 												archivo: "/ev/to/30/lunes.mp3",			fecha: `${year}-10-26` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, MARTES", 											archivo: "/ev/to/30/martes.mp3",		fecha: `${year}-10-27` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, MIÉRCOLES", 											archivo: "/ev/to/30/miércoles.mp3",		fecha: `${year}-10-28` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, JUEVES", 											archivo: "/ev/to/30/jueves.mp3",		fecha: `${year}-10-29` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, VIERNES", 											archivo: "/ev/to/30/viernes.mp3",		fecha: `${year}-10-30` },
/* OCTUBRE        */ { nombre: "Ordinario, Semana XXX, SÁBADO", 											archivo: "/ev/to/30/sábado.mp3",		fecha: `${year}-10-31` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, DOMINGO", 										archivo: "/ev/to/31/domingo.mp3",		fecha: `${year}-11-01` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, LUNES", 											archivo: "/ev/to/31/lunes.mp3",			fecha: `${year}-11-02` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, MARTES", 											archivo: "/ev/to/31/martes.mp3",		fecha: `${year}-11-03` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, MIÉRCOLES", 										archivo: "/ev/to/31/miércoles.mp3",		fecha: `${year}-11-04` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, JUEVES", 											archivo: "/ev/to/31/jueves.mp3",		fecha: `${year}-11-05` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, VIERNES", 										archivo: "/ev/to/31/viernes.mp3",		fecha: `${year}-11-06` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXI, SÁBADO", 											archivo: "/ev/to/31/sábado.mp3",		fecha: `${year}-11-07` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, DOMINGO", 										archivo: "/ev/to/32/domingo.mp3",		fecha: `${year}-11-08` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, LUNES", 											archivo: "/ev/to/32/lunes.mp3",			fecha: `${year}-11-09` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, MARTES", 										archivo: "/ev/to/32/martes.mp3",		fecha: `${year}-11-10` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, MIÉRCOLES", 										archivo: "/ev/to/32/miércoles.mp3",		fecha: `${year}-11-11` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, JUEVES", 										archivo: "/ev/to/32/jueves.mp3",		fecha: `${year}-11-12` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, VIERNES", 										archivo: "/ev/to/32/viernes.mp3",		fecha: `${year}-11-13` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXII, SÁBADO", 										archivo: "/ev/to/32/sábado.mp3",		fecha: `${year}-11-14` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, DOMINGO", 										archivo: "/ev/to/33/domingo.mp3",		fecha: `${year}-11-15` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, LUNES", 										archivo: "/ev/to/33/lunes.mp3",			fecha: `${year}-11-16` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, MARTES", 										archivo: "/ev/to/33/martes.mp3",		fecha: `${year}-11-17` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, MIÉRCOLES", 									archivo: "/ev/to/33/miércoles.mp3",		fecha: `${year}-11-18` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, JUEVES", 										archivo: "/ev/to/33/jueves.mp3",		fecha: `${year}-11-19` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, VIERNES", 										archivo: "/ev/to/33/viernes.mp3",		fecha: `${year}-11-20` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIII, SÁBADO", 										archivo: "/ev/to/33/sábado.mp3",		fecha: `${year}-11-21` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, DOMINGO", 										archivo: "/ev/to/34/domingo.mp3",		fecha: `${year}-11-22` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, LUNES", 											archivo: "/ev/to/34/lunes.mp3",			fecha: `${year}-11-23` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, MARTES", 										archivo: "/ev/to/34/martes.mp3",		fecha: `${year}-11-24` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, MIÉRCOLES", 										archivo: "/ev/to/34/miércoles.mp3",		fecha: `${year}-11-25` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, JUEVES", 										archivo: "/ev/to/34/jueves.mp3",		fecha: `${year}-11-26` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, VIERNES", 										archivo: "/ev/to/34/viernes.mp3",		fecha: `${year}-11-27` },
/* NOVIEMBRE        */ { nombre: "Ordinario, Semana XXXIV, SÁBADO", 										archivo: "/ev/to/34/sábado.mp3",		fecha: `${year}-11-28` },

/* NOVIEMBRE        */ { nombre: "Adviento, Semana I, DOMINGO", 											archivo: "/ev/ta/1/domingo.mp3",		fecha: `${year}-11-29` },
/* NOVIEMBRE        */ { nombre: "Adviento, Semana I, LUNES", 												archivo: "/ev/ta/1/lunes.mp3",			fecha: `${year}-11-30` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana I, MARTES", 												archivo: "/ev/ta/1/martes.mp3",			fecha: `${year}-12-01` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana I, MIÉRCOLES", 											archivo: "/ev/ta/1/miércoles.mp3",		fecha: `${year}-12-02` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana I, JUEVES", 												archivo: "/ev/ta/1/jueves.mp3",			fecha: `${year}-12-03` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana I, VIERNES", 											archivo: "/ev/ta/1/viernes.mp3",		fecha: `${year}-12-04` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana I, SÁBADO", 												archivo: "/ev/ta/1/sábado.mp3",			fecha: `${year}-12-05` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, DOMINGO", 											archivo: "/ev/ta/2/domingo.mp3",		fecha: `${year}-12-06` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, LUNES", 												archivo: "/ev/ta/2/lunes.mp3",			fecha: `${year}-12-07` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, La Inmaculada Concepción de la Bienaventurada siempre Virgen María, MARTES",	archivo: "/ev/ta/2/martes.mp3",			fecha: `${year}-12-08` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, MIÉRCOLES", 											archivo: "/ev/ta/2/miércoles.mp3",		fecha: `${year}-12-09` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, JUEVES", 											archivo: "/ev/ta/2/jueves.mp3",			fecha: `${year}-12-10` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, VIERNES", 											archivo: "/ev/ta/2/viernes.mp3",		fecha: `${year}-12-11` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana II, SÁBADO", 											archivo: "/ev/ta/2/sábado.mp3",			fecha: `${year}-12-12` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, DOMINGO", 											archivo: "/ev/ta/3/domingo.mp3",		fecha: `${year}-12-13` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, LUNES", 											archivo: "/ev/ta/3/lunes.mp3",			fecha: `${year}-12-14` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, MARTES", 											archivo: "/ev/ta/3/martes.mp3",			fecha: `${year}-12-15` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, MIÉRCOLES", 										archivo: "/ev/ta/3/miércoles.mp3",		fecha: `${year}-12-16` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, JUEVES", 											archivo: "/ev/ta/3/jueves.mp3",			fecha: `${year}-12-17` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, VIERNES", 											archivo: "/ev/ta/3/viernes.mp3",		fecha: `${year}-12-18` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana III, SÁBADO", 											archivo: "/ev/ta/3/sábado.mp3",			fecha: `${year}-12-19` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana IV, DOMINGO", 											archivo: "/ev/ta/4/domingo.mp3",		fecha: `${year}-12-20` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana IV, LUNES", 												archivo: "/ev/ta/4/lunes.mp3",			fecha: `${year}-12-21` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana IV, MARTES", 											archivo: "/ev/ta/4/martes.mp3",			fecha: `${year}-12-22` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana IV, MIÉRCOLES", 											archivo: "/ev/ta/4/miércoles.mp3",		fecha: `${year}-12-23` },
/* DICIEMBRE        */ { nombre: "Adviento, Semana IV, JUEVES", 											archivo: "/ev/ta/4/jueves.mp3",			fecha: `${year}-12-24` },

/* DICIEMBRE        * / { nombre: "Navidad, Semana I, La Natividad del Señor, VIERNES", 					archivo: "/ev/tn/25-NocheBuena.mp3",	fecha: `${year}-12-25` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana II, La Sagrada Familia de Jesús, María y José, SÁBADO", 	archivo: "/ev/tn/SagradaFamilia.mp3",	fecha: `${year}-12-26` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana III, Los Santos Inocentes, mártires, DOMINGO", 			archivo: "/ev/tn/27-sJuanAp.mp3",		fecha: `${year}-12-27` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana IV, LUNES", 												archivo: "/ev/tn/28-SanEsteban.mp3",	fecha: `${year}-12-28` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana V, MARTES", 												archivo: "/ev/tn/martes.mp3",			fecha: `${year}-12-29` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana VI, MIÉRCOLES", 											archivo: "/ev/tn/30-diciembre.mp3",		fecha: `${year}-12-30` },
/* DICIEMBRE        */ { nombre: "Navidad, Semana VII, JUEVES", 											archivo: "/ev/tn/31-diciembre.mp3",		fecha: `${year}-12-31` },



/*	Diciembre	/	{ nombre: "Adviento, Semana IV, Domingo",												archivo: "/ev/ta/4/domingo.mp3",		fecha: `${year}-12-21` }, */
/*	Diciembre	/	{ nombre: "Adviento, Semana IV, Lunes",													archivo: "/ev/ta/4/lunes.mp3",			fecha: `${year}-12-22` }, */
/*	Diciembre	/	{ nombre: "Adviento, Semana IV, Martes",												archivo: "/ev/ta/4/martes.mp3",			fecha: `${year}-12-23` }, */
/*	Diciembre	/	{ nombre: "Adviento, Semana IV, Miercoles",												archivo: "/ev/ta/4/miercoles.mp3",		fecha: `${year}-12-24` }, */

/*	Diciembre	*/	{ nombre: "Adviento, 21 de Diciembre",	    											archivo: "/ev/ta/4/21dic.mp3",		   	fecha: `${year}-12-21` },
/*	Diciembre	*/	{ nombre: "Adviento, 22 de Diciembre",	    											archivo: "/ev/ta/4/22dic.mp3",	    	fecha: `${year}-12-22` },
/*	Diciembre	*/	{ nombre: "Adviento, 23 de Diciembre",	    											archivo: "/ev/ta/4/23dic.mp3",		   	fecha: `${year}-12-23` },
/*	Diciembre	*/	{ nombre: "Adviento, 24 de Diciembre",	    											archivo: "/ev/ta/4/24dic.mp3",	    	fecha: `${year}-12-24` },
/*	Diciembre	*/	{ nombre: "Navidad, Semana I, Jueves",													archivo: "/ev/tn/25-NocheBuena.mp3",	fecha: `${year}-12-25` },
/*	Diciembre	*/	{ nombre: "Navidad, Fiesta de San Esteban, protomartir",								archivo: "/ev/tn/26-SanEsteban.mp3",	fecha: `${year}-12-26` },
/*	Diciembre	* /	{ nombre: "Navidad, San Juan Apostol",													archivo: "/ev/tn/27-sJuanAp.mp3",		fecha: `${year}-12-27` },

/*	Diciembre	*/	{ nombre: "Navidad, Domingo de la Sagrada Familia",										archivo: "/ev/tn/SagradaFamilia.mp3",	fecha: `${year}-12-27` },

/*	Diciembre	*/	{ nombre: "Navidad, Semana I, Lunes",													archivo: "/ev/tn/28-dic.mp3",			fecha: `${year}-12-28` },
/*	Diciembre	*/	{ nombre: "Navidad, Semana I, Martes",													archivo: "/ev/tn/29-dic.mp3",			fecha: `${year}-12-29` },
/*	Diciembre	*/	{ nombre: "Navidad, Semana I, Miercoles",												archivo: "/ev/tn/30-dic.mp3",			fecha: `${year}-12-30` },
/*	Diciembre	*/	{ nombre: "Navidad, 31 de Diciembre",													archivo: "/ev/tn/31-dic.mp3",			fecha: `${year}-12-31` },    
/*	Diciembre	* /	{ nombre: "Navidad, San Esteban",														archivo: "/ev/tn/28-SanEsteban.mp3",	fecha: `${year}-12-28` },*/

/*	Diciembre	* /	{ nombre: "Navidad, Domingo de la Sagrada Familia",										archivo: "/ev/tn/SagradaFamilia.mp3",	fecha: `${year}-12-28` },
/*	Diciembre	* /	{ nombre: "Navidad, Semana II, Lunes",													archivo: "/ev/tn/lunes.mp3",			fecha: `${year}-12-29` },
/*	Diciembre	* /	{ nombre: "Navidad, Semana II, Martes",													archivo: "/ev/tn/martes.mp3",			fecha: `${year}-12-30` },
/*	Diciembre	* /	{ nombre: "Navidad, 31 de Diciembre",													archivo: "/ev/tn/31-diciembre.mp3",		fecha: `${year}-12-31` }, */



];

function obtenerFechaHoy() {
    const hoy = new Date();
    const año = hoy.getFullYear();
    const mes = String(hoy.getMonth() + 1).padStart(2, '0');
    const dia = String(hoy.getDate()).padStart(2, '0');
    return `${año}-${mes}-${dia}`;
}

function cargarAudioPorDefecto() {
    const fechaHoy = obtenerFechaHoy();
    console.log("Fecha de hoy:", fechaHoy);

    const audioHoy = audios.find(audio => audio.fecha === fechaHoy);
    console.log("Audio encontrado:", audioHoy);

    const reproductor = document.getElementById('audio-player');
    const fuenteAudio = document.getElementById('audio-source');
    const tituloAudio = document.getElementById('titulo-audio');

    if (audioHoy) {
        console.log("Cargando audio:", audioHoy.archivo);
        tituloAudio.textContent = "Tiempo " + audioHoy.nombre; // Aquí agregas "Tiempo" delante del nombre
        fuenteAudio.src = audioHoy.archivo;
        reproductor.load();
    } else {
        console.log("No hay audio para hoy");
        tituloAudio.textContent = "Tiempo No hay audio para hoy"; // Aquí también agregas "Tiempo"
        fuenteAudio.src = "";
        reproductor.load();
    }
}

window.onload = cargarAudioPorDefecto;
