const year = new Date().getFullYear(); // Obtiene el año actual
// const year = 2025; // Si prefieres un año fijo

// Lista de audios con su información
const audios = [
    // DIA DE LOS SANTOS
    { nombre: "Santa María, Madre de Dios", 			archivo: "/salterios/src/evan/audios/01enero.mp3",		fecha: `${year}-01-01` }, // 1ro de Enero, Santa Maria Madre de Dios
    { nombre: "El Santísimo Nombre de Jesús", 			archivo: "/salterios/src/evan/audios/03enero.mp3",		fecha: `${year}-01-03` }, // 3 de Enero Santisimo Nombre de nuestro Señor Jesucristo
    { nombre: "La Epifanía del Señor", 					archivo: "/salterios/src/evan/audios/06enero.mp3",		fecha: `${year}-01-06` }, // 6 de Enero, Epifanía del Señor
    { nombre: "Día de la Altagracia", 					archivo: "/salterios/src/evan/audios/21enero.mp3",		fecha: `${year}-01-21` }, // 21 de Enero, Día de la Altagracia
    { nombre: "La Conversión de San Pablo, apóstol",	archivo: "/salterios/src/evan/audios/26enero.mp3",		fecha: `${year}-01-25` }, // 25 La Conversión de San Pablo, apóstol


/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tns01jueves.mp3",		fecha: `${year}-01-1` },
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 1 Viernes",		archivo: "/salterios/src/evan/audios/tns01viernes.mp3",		fecha: `${year}-01-2` },
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 1 Sabado",		archivo: "/salterios/src/evan/audios/tns01sabado.mp3",		fecha: `${year}-01-3` },
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 2 Domingo",		archivo: "/salterios/src/evan/audios/tns02domingo.mp3",		fecha: `${year}-01-4` },
/*	Enero		*/	{ nombre: "Tiempo Navidad, Semana 2 Lunes",			archivo: "/salterios/src/evan/audios/tns02lunes.mp3",		fecha: `${year}-01-5` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Martes",		archivo: "/salterios/src/evan/audios/tes02martes.mp3",		fecha: `${year}-01-6` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Miercoles",	archivo: "/salterios/src/evan/audios/tes02miercoles.mp3",	fecha: `${year}-01-7` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Jueves",		archivo: "/salterios/src/evan/audios/tes02jueves.mp3",		fecha: `${year}-01-8` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Viernes",		archivo: "/salterios/src/evan/audios/tes02viernes.mp3",		fecha: `${year}-01-9` },
/*	Enero		*/	{ nombre: "Tiempo Epifania, Semana 2 Sabado",		archivo: "/salterios/src/evan/audios/tes02sabado.mp3",		fecha: `${year}-01-10` },
/*		*/	
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Domingo",		archivo: "/salterios/src/evan/audios/tos01domingo.mp3",		fecha: `${year}-01-12` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Lunes",		archivo: "/salterios/src/evan/audios/tos01lunes.mp3",		fecha: `${year}-01-13` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Martes",		archivo: "/salterios/src/evan/audios/tos01martes.mp3",		fecha: `${year}-01-14` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Miercoles",	archivo: "/salterios/src/evan/audios/tos01miercoles.mp3",	fecha: `${year}-01-15` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tos01jueves.mp3",		fecha: `${year}-01-16` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Viernes", 	archivo: "/salterios/src/evan/audios/tos01viernes.mp3",		fecha: `${year}-01-17` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 1 Sabado", 		archivo: "/salterios/src/evan/audios/tos01sabado.mp3",		fecha: `${year}-01-18` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Domingo", 	archivo: "/salterios/src/evan/audios/tos02domingo.mp3",		fecha: `${year}-01-19` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Lunes", 		archivo: "/salterios/src/evan/audios/tos02lunes.mp3",		fecha: `${year}-01-20` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Martes", 		archivo: "/salterios/src/evan/audios/tos02martes.mp3",		fecha: `${year}-01-21` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Miercoles", 	archivo: "/salterios/src/evan/audios/tos02miercoles.mp3",	fecha: `${year}-01-22` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Jueves", 		archivo: "/salterios/src/evan/audios/tos02jueves.mp3",		fecha: `${year}-01-23` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Viernes", 	archivo: "/salterios/src/evan/audios/tos02viernes.mp3",		fecha: `${year}-01-24` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 2 Sabado", 		archivo: "/salterios/src/evan/audios/tos02sabado.mp3",		fecha: `${year}-01-25` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Domingo", 	archivo: "/salterios/src/evan/audios/tos03domingo.mp3",		fecha: `${year}-01-26` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Lunes", 		archivo: "/salterios/src/evan/audios/tos03lunes.mp3",		fecha: `${year}-01-27` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Martes", 		archivo: "/salterios/src/evan/audios/tos03martes.mp3",		fecha: `${year}-01-28` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Miercoles",	archivo: "/salterios/src/evan/audios/tos03miercoles.mp3",	fecha: `${year}-01-29` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Jueves",		archivo: "/salterios/src/evan/audios/tos03jueves.mp3",		fecha: `${year}-01-30` },
/*	Enero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Viernes",		archivo: "/salterios/src/evan/audios/tos03viernes.mp3",		fecha: `${year}-01-31` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 3 Sabado",		archivo: "/salterios/src/evan/audios/tos03sabado.mp3",		fecha: `${year}-02-1` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Domingo",		archivo: "/salterios/src/evan/audios/tos04domingo.mp3",		fecha: `${year}-02-2` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Lunes",		archivo: "/salterios/src/evan/audios/tos04lunes.mp3",		fecha: `${year}-02-3` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Martes",		archivo: "/salterios/src/evan/audios/tos04martes.mp3",		fecha: `${year}-02-4` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Miercoles",	archivo: "/salterios/src/evan/audios/tos04miercoles.mp3",	fecha: `${year}-02-5` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Jueves",		archivo: "/salterios/src/evan/audios/tos04jueves.mp3",		fecha: `${year}-02-6` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Viernes",		archivo: "/salterios/src/evan/audios/tos04viernes.mp3",		fecha: `${year}-02-7` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 4 Sabado",		archivo: "/salterios/src/evan/audios/tos04sabado.mp3",		fecha: `${year}-02-8` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Domingo",		archivo: "/salterios/src/evan/audios/tos05domingo.mp3",		fecha: `${year}-02-9` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Lunes",		archivo: "/salterios/src/evan/audios/tos05lunes.mp3",		fecha: `${year}-02-10` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Martes",		archivo: "/salterios/src/evan/audios/tos05martes.mp3",		fecha: `${year}-02-11` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Miercoles",	archivo: "/salterios/src/evan/audios/tos05miercoles.mp3",	fecha: `${year}-02-12` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Jueves",		archivo: "/salterios/src/evan/audios/tos05jueves.mp3",		fecha: `${year}-02-13` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Viernes",		archivo: "/salterios/src/evan/audios/tos05viernes.mp3",		fecha: `${year}-02-14` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 5 Sabado",		archivo: "/salterios/src/evan/audios/tos05sabado.mp3",		fecha: `${year}-02-15` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Domingo",		archivo: "/salterios/src/evan/audios/tos06domingo.mp3",		fecha: `${year}-02-16` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Lunes",		archivo: "/salterios/src/evan/audios/tos06lunes.mp3",		fecha: `${year}-02-17` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Martes",		archivo: "/salterios/src/evan/audios/tos06martes.mp3",		fecha: `${year}-02-18` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Miercoles",	archivo: "/salterios/src/evan/audios/tos06miercoles.mp3",	fecha: `${year}-02-19` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Jueves",		archivo: "/salterios/src/evan/audios/tos06jueves.mp3",		fecha: `${year}-02-20` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Viernes",		archivo: "/salterios/src/evan/audios/tos06viernes.mp3",		fecha: `${year}-02-21` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 6 Sabado",		archivo: "/salterios/src/evan/audios/tos06sabado.mp3",		fecha: `${year}-02-22` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Domingo",		archivo: "/salterios/src/evan/audios/tos07domingo.mp3",		fecha: `${year}-02-23` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Lunes",		archivo: "/salterios/src/evan/audios/tos07lunes.mp3",		fecha: `${year}-02-24` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Martes",		archivo: "/salterios/src/evan/audios/tos07martes.mp3",		fecha: `${year}-02-25` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Miercoles",	archivo: "/salterios/src/evan/audios/tos07miercoles.mp3",	fecha: `${year}-02-26` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Jueves",		archivo: "/salterios/src/evan/audios/tos07jueves.mp3",		fecha: `${year}-02-27` },
/*	Febrero		*/	{ nombre: "Tiempo Ordinario, Semana 7 Viernes",		archivo: "/salterios/src/evan/audios/tos07viernes.mp3",		fecha: `${year}-02-28` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 7 Sabado",		archivo: "/salterios/src/evan/audios/tos07sabado.mp3",		fecha: `${year}-03-1` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Domingo",		archivo: "/salterios/src/evan/audios/tos08domingo.mp3",		fecha: `${year}-03-2` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Lunes",		archivo: "/salterios/src/evan/audios/tos08lunes.mp3",		fecha: `${year}-03-3` },
/*	Marzo		*/	{ nombre: "Tiempo Ordinario, Semana 8 Martes",		archivo: "/salterios/src/evan/audios/tos08martes.mp3",		fecha: `${year}-03-4` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Miercoles Ceniza",		archivo: "/salterios/src/evan/audios/tcmiercolesceniza.mp3",fecha: `${year}-03-5` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Jueves",		archivo: "/salterios/src/evan/audios/tcs0dejueves.mp3",		fecha: `${year}-03-6` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Viernes",		archivo: "/salterios/src/evan/audios/tcs0deviernes.mp3",	fecha: `${year}-03-7` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana de Sabado",		archivo: "/salterios/src/evan/audios/tcs0desabado.mp3",		fecha: `${year}-03-8` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Domingo",		archivo: "/salterios/src/evan/audios/tcs01domingo.mp3",		fecha: `${year}-03-9` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Lunes",		archivo: "/salterios/src/evan/audios/tcs01lunes.mp3",		fecha: `${year}-03-10` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Martes",		archivo: "/salterios/src/evan/audios/tcs01martes.mp3",		fecha: `${year}-03-11` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Miercoles",	archivo: "/salterios/src/evan/audios/tcs01miercoles.mp3",	fecha: `${year}-03-12` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tcs01jueves.mp3",		fecha: `${year}-03-13` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Viernes",		archivo: "/salterios/src/evan/audios/tcs01viernes.mp3",		fecha: `${year}-03-14` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 1 Sabado",		archivo: "/salterios/src/evan/audios/tcs01sabado.mp3",		fecha: `${year}-03-15` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Domingo",		archivo: "/salterios/src/evan/audios/tcs02domingo.mp3",		fecha: `${year}-03-16` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Lunes",		archivo: "/salterios/src/evan/audios/tcs02lunes.mp3",		fecha: `${year}-03-17` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Martes",		archivo: "/salterios/src/evan/audios/tcs02martes.mp3",		fecha: `${year}-03-18` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Miercoles",	archivo: "/salterios/src/evan/audios/tcs02miercoles.mp3",	fecha: `${year}-03-19` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Jueves",		archivo: "/salterios/src/evan/audios/tcs02jueves.mp3",		fecha: `${year}-03-20` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Viernes",		archivo: "/salterios/src/evan/audios/tcs02viernes.mp3",		fecha: `${year}-03-21` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 2 Sabado",		archivo: "/salterios/src/evan/audios/tcs02sabado.mp3",		fecha: `${year}-03-22` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Domingo",		archivo: "/salterios/src/evan/audios/tcs03domingo.mp3",		fecha: `${year}-03-23` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Lunes",		archivo: "/salterios/src/evan/audios/tcs03lunes.mp3",		fecha: `${year}-03-24` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Martes",		archivo: "/salterios/src/evan/audios/tcs03martes.mp3",		fecha: `${year}-03-25` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Miercoles",	archivo: "/salterios/src/evan/audios/tcs03miercoles.mp3",	fecha: `${year}-03-26` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Jueves",		archivo: "/salterios/src/evan/audios/tcs03jueves.mp3",		fecha: `${year}-03-27` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Viernes",		archivo: "/salterios/src/evan/audios/tcs03viernes.mp3",		fecha: `${year}-03-28` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 3 Sabado",		archivo: "/salterios/src/evan/audios/tcs03sabado.mp3",		fecha: `${year}-03-29` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Domingo",		archivo: "/salterios/src/evan/audios/tcs04domingo.mp3",		fecha: `${year}-03-30` },
/*	Marzo		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Lunes",		archivo: "/salterios/src/evan/audios/tcs04lunes.mp3",		fecha: `${year}-03-31` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Martes",		archivo: "/salterios/src/evan/audios/tcs04martes.mp3",		fecha: `${year}-04-1` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Miercoles",	archivo: "/salterios/src/evan/audios/tcs04miercoles.mp3",	fecha: `${year}-04-2` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Jueves",		archivo: "/salterios/src/evan/audios/tcs04jueves.mp3",		fecha: `${year}-04-3` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Viernes",		archivo: "/salterios/src/evan/audios/tcs04viernes.mp3",		fecha: `${year}-04-4` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 4 Sabado",		archivo: "/salterios/src/evan/audios/tcs04sabado.mp3",		fecha: `${year}-04-5` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Domingo",		archivo: "/salterios/src/evan/audios/tcs05domingo.mp3",		fecha: `${year}-04-6` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Lunes",		archivo: "/salterios/src/evan/audios/tcs05lunes.mp3",		fecha: `${year}-04-7` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Martes",		archivo: "/salterios/src/evan/audios/tcs05martes.mp3",		fecha: `${year}-04-8` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Miercoles",	archivo: "/salterios/src/evan/audios/tcs05miercoles.mp3",	fecha: `${year}-04-9` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Jueves",		archivo: "/salterios/src/evan/audios/tcs05jueves.mp3",		fecha: `${year}-04-10` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Viernes",		archivo: "/salterios/src/evan/audios/tcs05viernes.mp3",		fecha: `${year}-04-11` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 5 Sabado",		archivo: "/salterios/src/evan/audios/tcs05sabado.mp3",		fecha: `${year}-04-12` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Domingo De Ramos",		archivo: "/salterios/src/evan/audios/tcs06domingo.mp3",		fecha: `${year}-04-13` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Lunes",		archivo: "/salterios/src/evan/audios/tcs06lunes.mp3",		fecha: `${year}-04-14` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Martes",		archivo: "/salterios/src/evan/audios/tcs06martes.mp3",		fecha: `${year}-04-15` },
/*	Abril		*/	{ nombre: "Tiempo Cuaresma, Semana 6 Miercoles",	archivo: "/salterios/src/evan/audios/tcs06miercoles.mp3",	fecha: `${year}-04-16` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Jueves",	archivo: "/salterios/src/evan/audios/tts06jueves.mp3",		fecha: `${year}-04-17` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Viernes",archivo: "/salterios/src/evan/audios/tts06viernes.mp3",		fecha: `${year}-04-18` },
/*	Abril		*/	{ nombre: "Tiempo Triduo Pascual, Semana 6 Sabado",	archivo: "/salterios/src/evan/audios/tts06sabado.mp3",		fecha: `${year}-04-19` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Domingo",		archivo: "/salterios/src/evan/audios/tps01domingo.mp3",		fecha: `${year}-04-20` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Lunes",			archivo: "/salterios/src/evan/audios/tps01lunes.mp3",		fecha: `${year}-04-21` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Martes",		archivo: "/salterios/src/evan/audios/tps01martes.mp3",		fecha: `${year}-04-22` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Miercoles",		archivo: "/salterios/src/evan/audios/tps01miercoles.mp3",	fecha: `${year}-04-23` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tps01jueves.mp3",		fecha: `${year}-04-24` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Viernes",		archivo: "/salterios/src/evan/audios/tps01viernes.mp3",		fecha: `${year}-04-25` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 1 Sabado",		archivo: "/salterios/src/evan/audios/tps01sabado.mp3",		fecha: `${year}-04-26` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Domingo",		archivo: "/salterios/src/evan/audios/tps02domingo.mp3",		fecha: `${year}-04-27` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Lunes",			archivo: "/salterios/src/evan/audios/tps02lunes.mp3",		fecha: `${year}-04-28` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Martes",		archivo: "/salterios/src/evan/audios/tps02martes.mp3",		fecha: `${year}-04-29` },
/*	Abril		*/	{ nombre: "Tiempo Pascual, Semana 2 Miercoles",		archivo: "/salterios/src/evan/audios/tps02miercoles.mp3",	fecha: `${year}-04-30` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Jueves",		archivo: "/salterios/src/evan/audios/tps02jueves.mp3",		fecha: `${year}-05-1` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Viernes",		archivo: "/salterios/src/evan/audios/tps02viernes.mp3",		fecha: `${year}-05-2` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 2 Sabado",		archivo: "/salterios/src/evan/audios/tps02sabado.mp3",		fecha: `${year}-05-3` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Domingo",		archivo: "/salterios/src/evan/audios/tps03domingo.mp3",		fecha: `${year}-05-4` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Lunes",			archivo: "/salterios/src/evan/audios/tps03lunes.mp3",		fecha: `${year}-05-5` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Martes",		archivo: "/salterios/src/evan/audios/tps03martes.mp3",		fecha: `${year}-05-6` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Miercoles",		archivo: "/salterios/src/evan/audios/tps03miercoles.mp3",	fecha: `${year}-05-7` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Jueves",		archivo: "/salterios/src/evan/audios/tps03jueves.mp3",		fecha: `${year}-05-8` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Viernes",		archivo: "/salterios/src/evan/audios/tps03viernes.mp3",		fecha: `${year}-05-9` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 3 Sabado",		archivo: "/salterios/src/evan/audios/tps03sabado.mp3",		fecha: `${year}-05-10` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Domingo",		archivo: "/salterios/src/evan/audios/tps04domingo.mp3",		fecha: `${year}-05-11` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Lunes",			archivo: "/salterios/src/evan/audios/tps04lunes.mp3",		fecha: `${year}-05-12` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Martes",		archivo: "/salterios/src/evan/audios/tps04martes.mp3",		fecha: `${year}-05-13` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Miercoles",		archivo: "/salterios/src/evan/audios/tps04miercoles.mp3",	fecha: `${year}-05-14` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Jueves",		archivo: "/salterios/src/evan/audios/tps04jueves.mp3",		fecha: `${year}-05-15` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Viernes",		archivo: "/salterios/src/evan/audios/tps04viernes.mp3",		fecha: `${year}-05-16` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 4 Sabado",		archivo: "/salterios/src/evan/audios/tps04sabado.mp3",		fecha: `${year}-05-17` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Domingo",		archivo: "/salterios/src/evan/audios/tps05domingo.mp3",		fecha: `${year}-05-18` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Lunes",			archivo: "/salterios/src/evan/audios/tps05lunes.mp3",		fecha: `${year}-05-19` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Martes",		archivo: "/salterios/src/evan/audios/tps05martes.mp3",		fecha: `${year}-05-20` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Miercoles",		archivo: "/salterios/src/evan/audios/tps05miercoles.mp3",	fecha: `${year}-05-21` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Jueves",		archivo: "/salterios/src/evan/audios/tps05jueves.mp3",		fecha: `${year}-05-22` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Viernes",		archivo: "/salterios/src/evan/audios/tps05viernes.mp3",		fecha: `${year}-05-23` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 5 Sabado",		archivo: "/salterios/src/evan/audios/tps05sabado.mp3",		fecha: `${year}-05-24` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Domingo",		archivo: "/salterios/src/evan/audios/tps06domingo.mp3",		fecha: `${year}-05-25` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Lunes",			archivo: "/salterios/src/evan/audios/tps06lunes.mp3",		fecha: `${year}-05-26` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Martes",		archivo: "/salterios/src/evan/audios/tps06martes.mp3",		fecha: `${year}-05-27` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Miercoles",		archivo: "/salterios/src/evan/audios/tps06miercoles.mp3",	fecha: `${year}-05-28` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Jueves",		archivo: "/salterios/src/evan/audios/tps06jueves.mp3",		fecha: `${year}-05-29` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Viernes",		archivo: "/salterios/src/evan/audios/tps06viernes.mp3",		fecha: `${year}-05-30` },
/*	Mayo		*/	{ nombre: "Tiempo Pascual, Semana 6 Sabado",		archivo: "/salterios/src/evan/audios/tps06sabado.mp3",		fecha: `${year}-05-31` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Domingo",		archivo: "/salterios/src/evan/audios/tps07domingo.mp3",		fecha: `${year}-06-1` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Lunes",			archivo: "/salterios/src/evan/audios/tps07lunes.mp3",		fecha: `${year}-06-2` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Martes",		archivo: "/salterios/src/evan/audios/tps07martes.mp3",		fecha: `${year}-06-3` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Miercoles",		archivo: "/salterios/src/evan/audios/tps07miercoles.mp3",	fecha: `${year}-06-4` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Jueves",		archivo: "/salterios/src/evan/audios/tps07jueves.mp3",		fecha: `${year}-06-5` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Viernes",		archivo: "/salterios/src/evan/audios/tps07viernes.mp3",		fecha: `${year}-06-6` },
/*	Junio		*/	{ nombre: "Tiempo Pascual, Semana 7 Sabado",		archivo: "/salterios/src/evan/audios/tps07sabado.mp3",		fecha: `${year}-06-7` },
/*	Junio		*/	{ nombre: "Pentecostes, Semana 10 Domingo",			archivo: "/salterios/src/evan/audios/tps010domingo.mp3",	fecha: `${year}-06-8` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Lunes",		archivo: "/salterios/src/evan/audios/tos010lunes.mp3",		fecha: `${year}-06-9` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Martes",		archivo: "/salterios/src/evan/audios/tos010martes.mp3",		fecha: `${year}-06-10` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Miercoles",	archivo: "/salterios/src/evan/audios/tos010miercoles.mp3",	fecha: `${year}-06-11` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Jueves",		archivo: "/salterios/src/evan/audios/tos010jueves.mp3",		fecha: `${year}-06-12` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Viernes",	archivo: "/salterios/src/evan/audios/tos010viernes.mp3",	fecha: `${year}-06-13` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 10 Sabado",		archivo: "/salterios/src/evan/audios/tos010sabado.mp3",		fecha: `${year}-06-14` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Domingo",	archivo: "/salterios/src/evan/audios/tos011domingo.mp3",	fecha: `${year}-06-15` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Lunes",		archivo: "/salterios/src/evan/audios/tos011lunes.mp3",		fecha: `${year}-06-16` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Martes",		archivo: "/salterios/src/evan/audios/tos011martes.mp3",		fecha: `${year}-06-17` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Miercoles",	archivo: "/salterios/src/evan/audios/tos011miercoles.mp3",	fecha: `${year}-06-18` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Jueves",		archivo: "/salterios/src/evan/audios/tos011jueves.mp3",		fecha: `${year}-06-19` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Viernes",	archivo: "/salterios/src/evan/audios/tos011viernes.mp3",	fecha: `${year}-06-20` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 11 Sabado",		archivo: "/salterios/src/evan/audios/tos011sabado.mp3",		fecha: `${year}-06-21` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Domingo",	archivo: "/salterios/src/evan/audios/tos012domingo.mp3",	fecha: `${year}-06-22` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Lunes",		archivo: "/salterios/src/evan/audios/tos012lunes.mp3",		fecha: `${year}-06-23` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Martes",		archivo: "/salterios/src/evan/audios/tos012martes.mp3",		fecha: `${year}-06-24` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Miercoles",	archivo: "/salterios/src/evan/audios/tos012miercoles.mp3",	fecha: `${year}-06-25` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Jueves",		archivo: "/salterios/src/evan/audios/tos012jueves.mp3",		fecha: `${year}-06-26` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Viernes",	archivo: "/salterios/src/evan/audios/tos012viernes.mp3",	fecha: `${year}-06-27` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 12 Sabado",		archivo: "/salterios/src/evan/audios/tos012sabado.mp3",		fecha: `${year}-06-28` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Domingo",	archivo: "/salterios/src/evan/audios/tos013domingo.mp3",	fecha: `${year}-06-29` },
/*	Junio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Lunes",		archivo: "/salterios/src/evan/audios/tos013lunes.mp3",		fecha: `${year}-06-30` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Martes",		archivo: "/salterios/src/evan/audios/tos013martes.mp3",		fecha: `${year}-07-1` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Miercoles",	archivo: "/salterios/src/evan/audios/tos013miercoles.mp3",	fecha: `${year}-07-2` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Jueves",		archivo: "/salterios/src/evan/audios/tos013jueves.mp3",		fecha: `${year}-07-3` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Viernes",	archivo: "/salterios/src/evan/audios/tos013viernes.mp3",	fecha: `${year}-07-4` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 13 Sabado",		archivo: "/salterios/src/evan/audios/tos013sabado.mp3",		fecha: `${year}-07-5` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Domingo",	archivo: "/salterios/src/evan/audios/tos014domingo.mp3",	fecha: `${year}-07-6` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Lunes",		archivo: "/salterios/src/evan/audios/tos014lunes.mp3",		fecha: `${year}-07-7` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Martes",		archivo: "/salterios/src/evan/audios/tos014martes.mp3",		fecha: `${year}-07-8` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Miercoles",	archivo: "/salterios/src/evan/audios/tos014miercoles.mp3",	fecha: `${year}-07-9` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Jueves",		archivo: "/salterios/src/evan/audios/tos014jueves.mp3",		fecha: `${year}-07-10` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Viernes",	archivo: "/salterios/src/evan/audios/tos014viernes.mp3",	fecha: `${year}-07-11` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 14 Sabado",		archivo: "/salterios/src/evan/audios/tos014sabado.mp3",		fecha: `${year}-07-12` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Domingo",	archivo: "/salterios/src/evan/audios/tos015domingo.mp3",	fecha: `${year}-07-13` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Lunes",		archivo: "/salterios/src/evan/audios/tos015lunes.mp3",		fecha: `${year}-07-14` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Martes",		archivo: "/salterios/src/evan/audios/tos015martes.mp3",		fecha: `${year}-07-15` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Miercoles",	archivo: "/salterios/src/evan/audios/tos015miercoles.mp3",	fecha: `${year}-07-16` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Jueves",		archivo: "/salterios/src/evan/audios/tos015jueves.mp3",		fecha: `${year}-07-17` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Viernes",	archivo: "/salterios/src/evan/audios/tos015viernes.mp3",	fecha: `${year}-07-18` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 15 Sabado",		archivo: "/salterios/src/evan/audios/tos015sabado.mp3",		fecha: `${year}-07-19` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Domingo",	archivo: "/salterios/src/evan/audios/tos016domingo.mp3",	fecha: `${year}-07-20` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Lunes",		archivo: "/salterios/src/evan/audios/tos016lunes.mp3",		fecha: `${year}-07-21` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Martes",		archivo: "/salterios/src/evan/audios/tos016martes.mp3",		fecha: `${year}-07-22` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Miercoles",	archivo: "/salterios/src/evan/audios/tos016miercoles.mp3",	fecha: `${year}-07-23` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Jueves",		archivo: "/salterios/src/evan/audios/tos016jueves.mp3",		fecha: `${year}-07-24` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Viernes",	archivo: "/salterios/src/evan/audios/tos016viernes.mp3",	fecha: `${year}-07-25` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 16 Sabado",		archivo: "/salterios/src/evan/audios/tos016sabado.mp3",		fecha: `${year}-07-26` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Domingo",	archivo: "/salterios/src/evan/audios/tos017domingo.mp3",	fecha: `${year}-07-27` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Lunes",		archivo: "/salterios/src/evan/audios/tos017lunes.mp3",		fecha: `${year}-07-28` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Martes",		archivo: "/salterios/src/evan/audios/tos017martes.mp3",		fecha: `${year}-07-29` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Miercoles",	archivo: "/salterios/src/evan/audios/tos017miercoles.mp3",	fecha: `${year}-07-30` },
/*	Julio		*/	{ nombre: "Tiempo Ordinario, Semana 17 Jueves",		archivo: "/salterios/src/evan/audios/tos017jueves.mp3",		fecha: `${year}-07-31` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 17 Viernes",	archivo: "/salterios/src/evan/audios/tos017viernes.mp3",	fecha: `${year}-08-1` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 17 Sabado",		archivo: "/salterios/src/evan/audios/tos017sabado.mp3",		fecha: `${year}-08-2` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Domingo",	archivo: "/salterios/src/evan/audios/tos018domingo.mp3",	fecha: `${year}-08-3` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Lunes",		archivo: "/salterios/src/evan/audios/tos018lunes.mp3",		fecha: `${year}-08-4` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Martes",		archivo: "/salterios/src/evan/audios/tos018martes.mp3",		fecha: `${year}-08-5` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Miercoles",	archivo: "/salterios/src/evan/audios/tos018miercoles.mp3",	fecha: `${year}-08-6` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Jueves",		archivo: "/salterios/src/evan/audios/tos018jueves.mp3",		fecha: `${year}-08-7` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Viernes",	archivo: "/salterios/src/evan/audios/tos018viernes.mp3",	fecha: `${year}-08-8` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 18 Sabado",		archivo: "/salterios/src/evan/audios/tos018sabado.mp3",		fecha: `${year}-08-9` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Domingo",	archivo: "/salterios/src/evan/audios/tos019domingo.mp3",	fecha: `${year}-08-10` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Lunes",		archivo: "/salterios/src/evan/audios/tos019lunes.mp3",		fecha: `${year}-08-11` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Martes",		archivo: "/salterios/src/evan/audios/tos019martes.mp3",		fecha: `${year}-08-12` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Miercoles",	archivo: "/salterios/src/evan/audios/tos019miercoles.mp3",	fecha: `${year}-08-13` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Jueves",		archivo: "/salterios/src/evan/audios/tos019jueves.mp3",		fecha: `${year}-08-14` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Viernes",	archivo: "/salterios/src/evan/audios/tos019viernes.mp3",	fecha: `${year}-08-15` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 19 Sabado",		archivo: "/salterios/src/evan/audios/tos019sabado.mp3",		fecha: `${year}-08-16` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Domingo",	archivo: "/salterios/src/evan/audios/tos020domingo.mp3",	fecha: `${year}-08-17` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Lunes",		archivo: "/salterios/src/evan/audios/tos020lunes.mp3",		fecha: `${year}-08-18` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Martes",		archivo: "/salterios/src/evan/audios/tos020martes.mp3",		fecha: `${year}-08-19` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Miercoles",	archivo: "/salterios/src/evan/audios/tos020miercoles.mp3",	fecha: `${year}-08-20` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Jueves",		archivo: "/salterios/src/evan/audios/tos020jueves.mp3",		fecha: `${year}-08-21` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Viernes",	archivo: "/salterios/src/evan/audios/tos020viernes.mp3",	fecha: `${year}-08-22` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 20 Sabado",		archivo: "/salterios/src/evan/audios/tos020sabado.mp3",		fecha: `${year}-08-23` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Domingo",	archivo: "/salterios/src/evan/audios/tos021domingo.mp3",	fecha: `${year}-08-24` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Lunes",		archivo: "/salterios/src/evan/audios/tos021lunes.mp3",		fecha: `${year}-08-25` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Martes",		archivo: "/salterios/src/evan/audios/tos021martes.mp3",		fecha: `${year}-08-26` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Miercoles",	archivo: "/salterios/src/evan/audios/tos021miercoles.mp3",	fecha: `${year}-08-27` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Jueves",		archivo: "/salterios/src/evan/audios/tos021jueves.mp3",		fecha: `${year}-08-28` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Viernes",	archivo: "/salterios/src/evan/audios/tos021viernes.mp3",	fecha: `${year}-08-29` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 21 Sabado",		archivo: "/salterios/src/evan/audios/tos021sabado.mp3",		fecha: `${year}-08-30` },
/*	Agosto		*/	{ nombre: "Tiempo Ordinario, Semana 22 Domingo",	archivo: "/salterios/src/evan/audios/tos022domingo.mp3",	fecha: `${year}-08-31` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Lunes",		archivo: "/salterios/src/evan/audios/tos022lunes.mp3",		fecha: `${year}-09-1` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Martes",		archivo: "/salterios/src/evan/audios/tos022martes.mp3",		fecha: `${year}-09-2` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Miercoles",	archivo: "/salterios/src/evan/audios/tos022miercoles.mp3",	fecha: `${year}-09-3` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Jueves",		archivo: "/salterios/src/evan/audios/tos022jueves.mp3",		fecha: `${year}-09-4` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Viernes",	archivo: "/salterios/src/evan/audios/tos022viernes.mp3",	fecha: `${year}-09-5` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 22 Sabado",		archivo: "/salterios/src/evan/audios/tos022sabado.mp3",		fecha: `${year}-09-6` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Domingo",	archivo: "/salterios/src/evan/audios/tos023domingo.mp3",	fecha: `${year}-09-7` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Lunes",		archivo: "/salterios/src/evan/audios/tos023lunes.mp3",		fecha: `${year}-09-8` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Martes",		archivo: "/salterios/src/evan/audios/tos023martes.mp3",		fecha: `${year}-09-9` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Miercoles",	archivo: "/salterios/src/evan/audios/tos023miercoles.mp3",	fecha: `${year}-09-10` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Jueves",		archivo: "/salterios/src/evan/audios/tos023jueves.mp3",		fecha: `${year}-09-11` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Viernes",	archivo: "/salterios/src/evan/audios/tos023viernes.mp3",	fecha: `${year}-09-12` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 23 Sabado",		archivo: "/salterios/src/evan/audios/tos023sabado.mp3",		fecha: `${year}-09-13` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Domingo",	archivo: "/salterios/src/evan/audios/tos024domingo.mp3",	fecha: `${year}-09-14` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Lunes",		archivo: "/salterios/src/evan/audios/tos024lunes.mp3",		fecha: `${year}-09-15` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Martes",		archivo: "/salterios/src/evan/audios/tos024martes.mp3",		fecha: `${year}-09-16` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Miercoles",	archivo: "/salterios/src/evan/audios/tos024miercoles.mp3",	fecha: `${year}-09-17` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Jueves",		archivo: "/salterios/src/evan/audios/tos024jueves.mp3",		fecha: `${year}-09-18` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Viernes",	archivo: "/salterios/src/evan/audios/tos024viernes.mp3",	fecha: `${year}-09-19` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 24 Sabado",		archivo: "/salterios/src/evan/audios/tos024sabado.mp3",		fecha: `${year}-09-20` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Domingo",	archivo: "/salterios/src/evan/audios/tos025domingo.mp3",	fecha: `${year}-09-21` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Lunes",		archivo: "/salterios/src/evan/audios/tos025lunes.mp3",		fecha: `${year}-09-22` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Martes",		archivo: "/salterios/src/evan/audios/tos025martes.mp3",		fecha: `${year}-09-23` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Miercoles",	archivo: "/salterios/src/evan/audios/tos025miercoles.mp3",	fecha: `${year}-09-24` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Jueves",		archivo: "/salterios/src/evan/audios/tos025jueves.mp3",		fecha: `${year}-09-25` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Viernes",	archivo: "/salterios/src/evan/audios/tos025viernes.mp3",	fecha: `${year}-09-26` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 25 Sabado",		archivo: "/salterios/src/evan/audios/tos025sabado.mp3",		fecha: `${year}-09-27` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Domingo",	archivo: "/salterios/src/evan/audios/tos026domingo.mp3",	fecha: `${year}-09-28` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Lunes",		archivo: "/salterios/src/evan/audios/tos026lunes.mp3",		fecha: `${year}-09-29` },
/*	Septiembre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Martes",		archivo: "/salterios/src/evan/audios/tos026martes.mp3",		fecha: `${year}-09-30` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Miercoles",		archivo: "/salterios/src/evan/audios/tos026miercoles.mp3",	fecha: `${year}-10-1` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Jueves",			archivo: "/salterios/src/evan/audios/tos026jueves.mp3",		fecha: `${year}-10-2` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Viernes",		archivo: "/salterios/src/evan/audios/tos026viernes.mp3",	fecha: `${year}-10-3` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 26 Sabado",			archivo: "/salterios/src/evan/audios/tos026sabado.mp3",		fecha: `${year}-10-4` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Domingo",		archivo: "/salterios/src/evan/audios/tos027domingo.mp3",	fecha: `${year}-10-5` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Lunes",			archivo: "/salterios/src/evan/audios/tos027lunes.mp3",		fecha: `${year}-10-6` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Martes",			archivo: "/salterios/src/evan/audios/tos027martes.mp3",		fecha: `${year}-10-7` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Miercoles",		archivo: "/salterios/src/evan/audios/tos027miercoles.mp3",	fecha: `${year}-10-8` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Jueves",			archivo: "/salterios/src/evan/audios/tos027jueves.mp3",		fecha: `${year}-10-9` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Viernes",		archivo: "/salterios/src/evan/audios/tos027viernes.mp3",	fecha: `${year}-10-10` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 27 Sabado",			archivo: "/salterios/src/evan/audios/tos027sabado.mp3",		fecha: `${year}-10-11` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Domingo",		archivo: "/salterios/src/evan/audios/tos028domingo.mp3",	fecha: `${year}-10-12` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Lunes",			archivo: "/salterios/src/evan/audios/tos028lunes.mp3",		fecha: `${year}-10-13` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Martes",			archivo: "/salterios/src/evan/audios/tos028martes.mp3",		fecha: `${year}-10-14` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Miercoles",		archivo: "/salterios/src/evan/audios/tos028miercoles.mp3",	fecha: `${year}-10-15` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Jueves",			archivo: "/salterios/src/evan/audios/tos028jueves.mp3",		fecha: `${year}-10-16` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Viernes",		archivo: "/salterios/src/evan/audios/tos028viernes.mp3",	fecha: `${year}-10-17` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 28 Sabado",			archivo: "/salterios/src/evan/audios/tos028sabado.mp3",		fecha: `${year}-10-18` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Domingo",		archivo: "/salterios/src/evan/audios/tos029domingo.mp3",	fecha: `${year}-10-19` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Lunes",			archivo: "/salterios/src/evan/audios/tos029lunes.mp3",		fecha: `${year}-10-20` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Martes",			archivo: "/salterios/src/evan/audios/tos029martes.mp3",		fecha: `${year}-10-21` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Miercoles",		archivo: "/salterios/src/evan/audios/tos029miercoles.mp3",	fecha: `${year}-10-22` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Jueves",			archivo: "/salterios/src/evan/audios/tos029jueves.mp3",		fecha: `${year}-10-23` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Viernes",		archivo: "/salterios/src/evan/audios/tos029viernes.mp3",	fecha: `${year}-10-24` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 29 Sabado",			archivo: "/salterios/src/evan/audios/tos029sabado.mp3",		fecha: `${year}-10-25` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Domingo",		archivo: "/salterios/src/evan/audios/tos030domingo.mp3",	fecha: `${year}-10-26` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Lunes",			archivo: "/salterios/src/evan/audios/tos030lunes.mp3",		fecha: `${year}-10-27` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Martes",			archivo: "/salterios/src/evan/audios/tos030martes.mp3",		fecha: `${year}-10-28` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Miercoles",		archivo: "/salterios/src/evan/audios/tos030miercoles.mp3",	fecha: `${year}-10-29` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Jueves",			archivo: "/salterios/src/evan/audios/tos030jueves.mp3",		fecha: `${year}-10-30` },
/*	Octubre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Viernes",		archivo: "/salterios/src/evan/audios/tos030viernes.mp3",	fecha: `${year}-10-31` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 30 Sabado",		archivo: "/salterios/src/evan/audios/tos030sabado.mp3",		fecha: `${year}-11-1` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Domingo",	archivo: "/salterios/src/evan/audios/tos031domingo.mp3",	fecha: `${year}-11-2` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Lunes",		archivo: "/salterios/src/evan/audios/tos031lunes.mp3",		fecha: `${year}-11-3` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Martes",		archivo: "/salterios/src/evan/audios/tos031martes.mp3",		fecha: `${year}-11-4` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Miercoles",	archivo: "/salterios/src/evan/audios/tos031miercoles.mp3",	fecha: `${year}-11-5` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Jueves",		archivo: "/salterios/src/evan/audios/tos031jueves.mp3",		fecha: `${year}-11-6` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Viernes",	archivo: "/salterios/src/evan/audios/tos031viernes.mp3",	fecha: `${year}-11-7` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 31 Sabado",		archivo: "/salterios/src/evan/audios/tos031sabado.mp3",		fecha: `${year}-11-8` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Domingo",	archivo: "/salterios/src/evan/audios/tos032domingo.mp3",	fecha: `${year}-11-9` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Lunes",		archivo: "/salterios/src/evan/audios/tos032lunes.mp3",		fecha: `${year}-11-10` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Martes",		archivo: "/salterios/src/evan/audios/tos032martes.mp3",		fecha: `${year}-11-11` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Miercoles",	archivo: "/salterios/src/evan/audios/tos032miercoles.mp3",	fecha: `${year}-11-12` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Jueves",		archivo: "/salterios/src/evan/audios/tos032jueves.mp3",		fecha: `${year}-11-13` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Viernes",	archivo: "/salterios/src/evan/audios/tos032viernes.mp3",	fecha: `${year}-11-14` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 32 Sabado",		archivo: "/salterios/src/evan/audios/tos032sabado.mp3",		fecha: `${year}-11-15` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Domingo",	archivo: "/salterios/src/evan/audios/tos033domingo.mp3",	fecha: `${year}-11-16` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Lunes",		archivo: "/salterios/src/evan/audios/tos033lunes.mp3",		fecha: `${year}-11-17` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Martes",		archivo: "/salterios/src/evan/audios/tos033martes.mp3",		fecha: `${year}-11-18` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Miercoles",	archivo: "/salterios/src/evan/audios/tos033miercoles.mp3",	fecha: `${year}-11-19` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Jueves",		archivo: "/salterios/src/evan/audios/tos033jueves.mp3",		fecha: `${year}-11-20` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Viernes",	archivo: "/salterios/src/evan/audios/tos033viernes.mp3",	fecha: `${year}-11-21` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 33 Sabado",		archivo: "/salterios/src/evan/audios/tos033sabado.mp3",		fecha: `${year}-11-22` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Domingo",	archivo: "/salterios/src/evan/audios/tos034domingo.mp3",	fecha: `${year}-11-23` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Lunes",		archivo: "/salterios/src/evan/audios/tos034lunes.mp3",		fecha: `${year}-11-24` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Martes",		archivo: "/salterios/src/evan/audios/tos034martes.mp3",		fecha: `${year}-11-25` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Miercoles",	archivo: "/salterios/src/evan/audios/tos034miercoles.mp3",	fecha: `${year}-11-26` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Jueves",		archivo: "/salterios/src/evan/audios/tos034jueves.mp3",		fecha: `${year}-11-27` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Viernes",	archivo: "/salterios/src/evan/audios/tos034viernes.mp3",	fecha: `${year}-11-28` },
/*	Noviembre	*/	{ nombre: "Tiempo Ordinario, Semana 34 Sabado",		archivo: "/salterios/src/evan/audios/tos034sabado.mp3",		fecha: `${year}-11-29` },
/*	Noviembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Domingo",		archivo: "/salterios/src/evan/audios/tas01domingo.mp3",		fecha: `${year}-11-30` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Lunes",		archivo: "/salterios/src/evan/audios/tas01lunes.mp3",		fecha: `${year}-12-1` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Martes",		archivo: "/salterios/src/evan/audios/tas01martes.mp3",		fecha: `${year}-12-2` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Miercoles",	archivo: "/salterios/src/evan/audios/tas01miercoles.mp3",	fecha: `${year}-12-3` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tas01jueves.mp3",		fecha: `${year}-12-4` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Viernes",		archivo: "/salterios/src/evan/audios/tas01viernes.mp3",		fecha: `${year}-12-5` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 1 Sabado",		archivo: "/salterios/src/evan/audios/tas01sabado.mp3",		fecha: `${year}-12-6` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Domingo",		archivo: "/salterios/src/evan/audios/tas02domingo.mp3",		fecha: `${year}-12-7` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Lunes",		archivo: "/salterios/src/evan/audios/tas02lunes.mp3",		fecha: `${year}-12-8` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Martes",		archivo: "/salterios/src/evan/audios/tas02martes.mp3",		fecha: `${year}-12-9` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Miercoles",	archivo: "/salterios/src/evan/audios/tas02miercoles.mp3",	fecha: `${year}-12-10` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Jueves",		archivo: "/salterios/src/evan/audios/tas02jueves.mp3",		fecha: `${year}-12-11` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Viernes",		archivo: "/salterios/src/evan/audios/tas02viernes.mp3",		fecha: `${year}-12-12` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 2 Sabado",		archivo: "/salterios/src/evan/audios/tas02sabado.mp3",		fecha: `${year}-12-13` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Domingo",		archivo: "/salterios/src/evan/audios/tas03domingo.mp3",		fecha: `${year}-12-14` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Lunes",		archivo: "/salterios/src/evan/audios/tas03lunes.mp3",		fecha: `${year}-12-15` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Martes",		archivo: "/salterios/src/evan/audios/tas03martes.mp3",		fecha: `${year}-12-16` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Miercoles",	archivo: "/salterios/src/evan/audios/tas03miercoles.mp3",	fecha: `${year}-12-17` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Jueves",		archivo: "/salterios/src/evan/audios/tas03jueves.mp3",		fecha: `${year}-12-18` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Viernes",		archivo: "/salterios/src/evan/audios/tas03viernes.mp3",		fecha: `${year}-12-19` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 3 Sabado",		archivo: "/salterios/src/evan/audios/tas03sabado.mp3",		fecha: `${year}-12-20` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Domingo",		archivo: "/salterios/src/evan/audios/tas04domingo.mp3",		fecha: `${year}-12-21` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Lunes",		archivo: "/salterios/src/evan/audios/tas04lunes.mp3",		fecha: `${year}-12-22` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Martes",		archivo: "/salterios/src/evan/audios/tas04martes.mp3",		fecha: `${year}-12-23` },
/*	Diciembre	*/	{ nombre: "Tiempo Adviento, Semana 4 Miercoles",	archivo: "/salterios/src/evan/audios/tas04miercoles.mp3",	fecha: `${year}-12-24` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Jueves",		archivo: "/salterios/src/evan/audios/tns01jueves.mp3",		fecha: `${year}-12-25` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Viernes",		archivo: "/salterios/src/evan/audios/tns01viernes.mp3",		fecha: `${year}-12-26` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 1 Sabado",		archivo: "/salterios/src/evan/audios/tns01sabado.mp3",		fecha: `${year}-12-27` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Domingo",		archivo: "/salterios/src/evan/audios/tns02domingo.mp3",		fecha: `${year}-12-28` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Lunes",			archivo: "/salterios/src/evan/audios/tns02lunes.mp3",		fecha: `${year}-12-29` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Martes",		archivo: "/salterios/src/evan/audios/tns02martes.mp3",		fecha: `${year}-12-30` },
/*	Diciembre	*/	{ nombre: "Tiempo Navidad, Semana 2 Miercoles",		archivo: "/salterios/src/evan/audios/tns02miercoles.mp3",	fecha: `${year}-12-31` },

	
];

function obtenerFechaHoy() {
    const hoy = new Date();
    const año = hoy.getFullYear();
    const mes = String(hoy.getMonth() + 1).padStart(2, '0');
    const dia = String(hoy.getDate()).padStart(2, '0');
    return `${año}-${mes}-${dia}`;
}

function cargarAudioPorDefecto() {
    const		fechaHoy = obtenerFechaHoy();
    console.log("Fecha de hoy:",		fechaHoy);

    const audioHoy = audios.find(audio => audio.fecha ===		fechaHoy);
    console.log("Audio encontrado:", audioHoy);

    const reproductor = document.getElementById('audio-player');
    const fuenteAudio = document.getElementById('audio-source');
    const tituloAudio = document.getElementById('titulo-audio');

    if (audioHoy) {
        console.log("Cargando audio:", audioHoy.archivo);
        tituloAudio.textContent = audioHoy.nombre;
        fuenteAudio.src = audioHoy.archivo;
        reproductor.load();
    } else {
        console.log("No hay audio para hoy");
        tituloAudio.textContent = "No hay audio para hoy";
        fuenteAudio.src = "";
        reproductor.load();
    }
}

window.onload = cargarAudioPorDefecto;